### ISSUE TITLE
wont install on mac OSX

### ISSUE THREAD

**Issue by arun057** [aerospike/aerospike-client-nodejs#1]
When trying to run the examples from a mac, npm install fails. 

```
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: aerospike@1.0.0
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "install" "../"
npm ERR! cwd ~/aerospike-client-nodejs/examples
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code EBADPLATFORM
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     ~/aerospike-client-nodejs/examples/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ankurjasoria** [comment]
Wont install on Windows7
When using below link for NodeJS with windows7 and run this command "$ npm install aerospike"
http://www.aerospike.com/docs/client/nodejs/install/

Error Message :
C:\nodecellar> npm install aerospike
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: aerospike@1.0.26
npm ERR! notsup Valid OS: linux,darwin
npm ERR! notsup Valid Arch: x64
npm ERR! notsup Actual OS: win32
npm ERR! notsup Actual Arch: ia32

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\
\npm-cli.js" "install" "aerospike"
npm ERR! cwd C:\nodecellar
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code EBADPLATFORM
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! C:\nodecellar\npm-debug.log
npm ERR! not ok code 0
C:\nodecellar>
