### ISSUE TITLE
Is there a skip() available ?

### ISSUE THREAD

**Issue by pravin-d** [aerospike/aerospike-client-nodejs#101]
For pagination primary requirements are orderBy, limit and skip (coming from sql world). Is there a plan for the same ?

**Comment by jhecking** [comment]
@pravin-d, there is currently no support for pagination in the aerospike API. Depending on your specific use case you might find some ideas for possible solutions/work-arounds in this thread on our forums: https://discuss.aerospike.com/t/pagination-in-fetched-result-set-from-aerospike/911.
