### ISSUE TITLE
discuss: graph query language

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [aerospike/aerospike-client-nodejs#109]
have you ever had a discussion concerning building a graph QL on top of the current C/C+/node client. I've see this has been done for `leveldb` in js. Obviously the `db` is not built for that purpose, but I was wondering whether one could emulate such a behaviour w/ indexes etc.

**Comment by mrbar42** [comment]
graph QL is designed to support any backend
With aerospike you will probably need more sets to compensate for the lack of complex queries

take this SQL example - I can totally imagine implementation of this using aerospike.
It might take more than one query - but it should bother anyone
```javascript
const User = new GraphQLObjectType({
  name: 'User',
  fields: () => ({
    id: {
      type: GraphQLID
    },
    name: {
      type: GraphQLString
    },
    stories: {
      type: new GraphQLList(Story),
      resolve(parent, args, {rootValue: {db}}) {
        return db.all(`
          SELECT * FROM Story WHERE author = $user
        `, {$user: parent.id});
      }
    }
  })
});
```

**Comment by jhecking** [comment]
Yes, there have been discussions. One possible approach would be to use Aerospike as the storage backend for the [Titan Distributed Graph Database](https://thinkaurelius.github.io/titan/). But it's currently not on our roadmap.

**Comment by eljefedelrodeodeljefe** [comment]
Call will have a look. I think we can close this for the while.
