### ISSUE TITLE
Return undefined for error on success

### ISSUE THREAD

**Issue by AlgoTrader** [aerospike/aerospike-client-nodejs#11]
Node.js provide the standard way of things that you break in aerospike module. The standard node way or reporting errors is providing err as the first parameter of callbacks.

If there is no error, then err is null or underfined, not {code:0, message:null, func:null, ...}. Providing error object with OK code is very odd way of implementing stuff in node

**Comment by rschmukler** [comment]
Just chiming in that this is very much an antipattern within node and that for things that assume `falsy` values (like libraries that convert callbacks to thunks/promises) it breaks them. +1 for changing it. No opinion on `null` vs `undefined` (`null` does feel more "node") but it should definitely not be an object on success.

**Comment by EmilTholin** [comment]
+1 Aerospike is phenomenal, but this issue makes the Node driver very unpleasant to work with. It breaks the convention, and it makes it [hard to wrap with bluebird](http://stackoverflow.com/questions/34075815/add-custom-then-method-to-every-function-generated-by-promisifyall?noredirect=1#comment55907085_34075815). Maybe you could include a flag when initializing the client, if not changing it altogether?

var client = aerospike.client({
    hosts: [ { addr: '127.0.0.1', port: 3000 } ],
    standardNodeError: true // error === undefined upon success
});

**Comment by eljefedelrodeodeljefe** [comment]
This currently really stands in my way to really dive into aerospike 100% will a PR be quickly welcomed? @cstivers78

There is a similar issue with (the user incorrectly) passing, taht floats breaking the client or similar.

**Comment by jhecking** [comment]
@eljefedelrodeodeljefe, a pull request would be welcome! As Chris had pointed out this is a backwards incompatible change and can potentially affect existing client code. So we need to be mindful of this. Maybe you can open a PR and quickly describe the changes you plan to do? I'd be happy to work with you on this.

**Comment by eljefedelrodeodeljefe** [comment]
@jhecking moved this to #105

**Comment by jhecking** [comment]
For v2 of the Aerospike Node.js client we have changed the semantics of the callbacks done by the client to follow the Node.js error-first callback semantics where the error argument is `null` if the operation was successful. v2 is now available as a pre-release in version `2.0.0-alpha.1` on npmjs.com.

Some additional resources:
* [Pre-release announcement](http://www.aerospike.com/blog/early-adopter-release-for-aerospike-node-js-client-v2-0/)
* [Changelog](https://github.com/aerospike/aerospike-client-nodejs/blob/master/History.md)
* List of [backward incompatible changes](https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/api-changes.md)
