### ISSUE TITLE
error: Fedora 23 is not supported

### ISSUE THREAD

**Issue by msilberg** [aerospike/aerospike-client-nodejs#113]
Unable to build the client in Fedora 23, running kernel version `4.3.5-300.fc23.x86_64`.

I get the following error:

```
npm install
> aerospike@1.0.56 install ~/src/myproject/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '~/src/myproject/node_modules/aerospike/build'
  TOUCH binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
error: fedora23 is not supported.
```

**Comment by jhecking** [comment]
@msilberg, do you mind try adding `fedora23` to the list of supported distros in [`script/aerospike_client_c.sh`](https://github.com/aerospike/aerospike-client-nodejs/blob/master/scripts/aerospike-client-c.sh#L54) and see if there are any actual issues building the client?

**Comment by jhecking** [comment]
@msilberg, you should be able to install `aerospike@1.0.57` on Fedora 23. Can you please give this a try and let me know if there are still any issues?
