### ISSUE TITLE
Aerospike will not install on Korora

### ISSUE THREAD

**Issue by cable2T17** [aerospike/aerospike-client-nodejs#115]
When installing aerospike on Korora, a fedora remix, it errors because "Korora is not supported".

[npm-debug.txt](https://github.com/aerospike/aerospike-client-nodejs/files/147731/npm-debug.txt)

**Comment by jhecking** [comment]
@cable2T17, you should be able to install `aerospike@1.0.57` on Korora 22/23. Can you please give this a try and let me know if there are still any issues?
