### ISSUE TITLE
Event loop does not get released if module gets required but never used to open & close client connection

### ISSUE THREAD

**Issue by djMax** [aerospike/aerospike-client-nodejs#124]
The following tape test never exits:

```
import tape from 'tape';
import aerospike from 'aerospike';

tape.test('hello', (t) => {
    t.end();
});
```

**Comment by djMax** [comment]
Do we **have** to call releaseEventLoop now? Seems so, but the docs are very unclear on this topic...

**Comment by djMax** [comment]
I think there's a bug and a questionable design decision at work here.

The bug:
https://github.com/aerospike/aerospike-client-nodejs/blob/master/lib/client.js#L366

The problem is if I'm not connected yet, releaseEventLoop will never get called and the app will never quit. This is happening (unsurprisingly) in unit tests, but in theory could happen in a variety of other situations.

The bad design decision:
In trying to figure this out I was paring down the test infrastructure as far as possible. To the point that I had this:
```
var a = require('aerospike');
```

That will hang forever, because there's nobody calling releaseEventLoop. IMHO, "require" should not be enough to do this. It would seem the better thing to do is create the event loop resources on first client creation (and fix the other bug). Since node is single threaded, it seems like a simple latching variable in client.js should be enough, but obviously there may be more to your use of the event loop than I can see.

**Comment by jhecking** [comment]
> It would seem the better thing to do is create the event loop resources on first client creation.

Agree. I will change this.

>  and fix the other bug

I'm not clear what other bug you are referring to? Can you elaborate?

> Do we have to call releaseEventLoop now? Seems so, but the docs are very unclear on this topic...

Are you referring to the new [API docs](http://www.aerospike.com/apidocs/nodejs/module-aerospike.html#-static-releaseEventLoop__anchor), or the documentation at http://www.aerospike.com/docs/client/nodejs/?

Btw, I don't think this problem is specific to Node.js. The behavior should be the same on all Node.js versions.
