### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by samlane** [aerospike/aerospike-client-nodejs#128]
Attempting to set up NodeJS application to connect to Aerospike, and I hit an error I can't find a solution to.

Basically, I connect as such:

```
var client = Aerospike.client({
        hosts: [{addr: '10.10.128.48', port: 3000}],
        log: {level: Aerospike.log.DEBUG}
});
client.connect(function (error) {
  if (error) {
        console.log('Connection to Aerospike cluster failed!')
  } else {
        console.log('Connection to Aerospike cluster succeeded!')
  }
});
Then as part of processing a command, I attempt to issue a put:

    var key = new Aerospike.Key('test22', 'node_set', accessKey);

    var rec = {
            sid: 'ABCDEF99',
            site_id: 1,
            language_id: 2
    };

    client.put(key, rec, function(err) {
            if (err) {
                    console.log("Error: %s", err.message);
                    callbackFunc(err, res, null);
            }
            else {
                    console.log("Create success");
                    callbackFunc(err, res, session);
            }
    });
```
Output:

```
May 09 2016 20:58:19 GMT: DEBUG(32599) [client.cc:115] [New] - Aerospike object initialization : success
May 09 2016 20:58:19 GMT: DEBUG(32599) [cluster.cc:52] [Connect] - Connecting to Cluster: Success
Connection to Aerospike cluster succeeded!
PORT defined as undefined
Binding to port 9001
May 09 2016 20:58:24 GMT: DEBUG(32599) [put_async.cc:81] [PutAsync] - Sending async put command

May 09 2016 20:58:24 GMT: DEBUG(32599) [async.cc:165] [async_write_listener] - Command failed: -6 uv_tcp_connect failed: unknown error
May 09 2016 20:58:24 GMT: DEBUG(32599) [async.cc:171] [async_write_listener] - Invoking JS callback function
Error: uv_tcp_connect failed: unknown error
Segmentation fault (core dumped)
```
I assume this to mean that the initial connection succeeds, but it appears to be a connection error when it attempts the PUT. I'm not sure where to look for further info to debug.

I'm running this on CentOS 7.2.  Node v0.10.42, and Aerospike module 2.0.4

Thanks,
Sam

**Comment by jhecking** [comment]
Hi Sam,

Aerospike Node.js Client v2 no longer supports Node v0.10 due to incompatibilities with the bundled libuv versions. (Node v0.10 uses a very old pre-1.0 version of libuv.) Is there any possibility you can upgrade to Node v4 or later?

Cheers,
Jan

**Comment by bbulkow** [comment]
Sam - if you'd like to stay in the 0.xx world, can you consider v0.12.x ? Aerospike supports that, just not the v0.10 world, due to the libuv compatibility issues Jan mentioned.

**Comment by samlane** [comment]
Thanks.  I did install Node 4.4 from source and no longer hit this error.

**Comment by kinghadi** [comment]
I have the same problem. I have `nodejs v6.1.0 ` and aerospike node js `lv2.1.1`. I removed `node_modules` and also `npm rebuild`. But nothing worked! We are using `redis` and we want to migrate to `aerospike`. Thank you

**Comment by jhecking** [comment]
@kinghadi, if you are already using Node.js v6, then the error you are seeing is likely different from the one Sam reported. Can you please open a new issue and post the error message that you are seeing? If possible, please also share the parts of the code where the error occurs.
