### ISSUE TITLE
Max node/event loop [...] async connections would be exceeded: 300

### ISSUE THREAD

**Issue by blitzprog** [aerospike/aerospike-client-nodejs#130]
I'm getting the error `Unhandled rejection AerospikeError: Max node/event loop [...] async connections would be exceeded: 300` on scan operations.
How can I overwrite this limit or fix the problem?

**Comment by jhecking** [comment]
The Node.js client currently does not expose this as a configurable setting. Can you describe you use case a bit more? What kind of operation do you perform inside the data event handler? One possible option that might be more efficient is to perform the changes using a User Defined Function (UDF) on the server. You can find more information in the [technical documentation](http://www.aerospike.com/docs/guide/record_udf.html). But it depends on whether you have all the information available server side that you need.

**Comment by blitzprog** [comment]
I'll try to describe my use case once I find some free time.

However this error did never occur in Aerospike 1.x client.
It only appeared after upgrading my code to Aerospike 2.x node client.

**Comment by jhecking** [comment]
The scan implementation in Aerospike Node.js v1.x is very inefficient. Despite the asynchronous interface it's actually using synchronous, i.e. blocking I/O internally. Scan operations in v1.x often block the event loop and can cause excessive memory consumption. I've described this in much more detail in a recent [blog post](http://www.aerospike.com/blog/win-win-greater-speed-and-lower-latency-with-aerospikes-node-js-client-v2-0/).

Single key operations in v1 — such as PUT — use synchronous, blocking I/O as well. They are executed in libuv worker threads. Therefore the parallelism is limited by the size of the libuv threadpool, which is 4 by default.

**Comment by csimi** [comment]
I'm running into the same issue on 2.1.1 client.
Aerospike is used as a simple K-V cache (I store {value: 'longstringhere'} objects on the server).
I'm doing around 10-20k set operations/s over 10 8 threaded machines.
Other than that I use batchRead to read values, with up to 1000-1500 keys in a single call (this should be only 1 connection though).
Maybe somehow the integration of Node and the C client can't take the concurrency? This kind of workload should be pancakes for either Node.js or C.

**Comment by jhecking** [comment]
It's not possible to change the limit in v2.1.1 at the moment. But I've just committed a change (d26e7a38cbb20a7e9c85a51b03065067042590da) to add a new `maxConnsPerNode` setting in the client's configuration. This will be included in the next release.

**Comment by csimi** [comment]
Thank you, the issue completely disappeared with a higher limit.

**Comment by jhecking** [comment]
Closing the issue. @blitzprog, feel free to reopen if this does not fully resolve your problem yet.

**Comment by jhecking** [comment]
This is included in v2.2.0 which is available on npmjs.org now.

**Comment by lbabiera** [comment]
Pardon me, I'm very new to aerospike, I also encountered this issue. I updated my aerospike node js client to v2.2.0 but cannot seem to find where to set maxConnsPerNode to a higher limit to resolve the issue.

**Comment by jhecking** [comment]
@lbabiera, it's part of the client config that you pass to `Aerospike.connect()`:

```
const Aerospike = require('aerospike')
const config = {
  maxConnsPerNode: 1000
}
Aerospike.connect(config, (error, client) => {...})
```

**Comment by lbabiera** [comment]
Hi jhecking,

Thanks for the reply. However, when I applied this change I got the error message below.

 return callback(null, arg1, arg2, arg3)
           ^
TypeError: object is not a function
    at Client.DefaultCallbackHandler [as callbackHandler] (/usr/local/src/ACS/node_modules/aerospike/lib/client.js:74:12)
    at connectCb (/usr/local/src/ACS/node_modules/aerospike/lib/client.js:422:10)
    at Client.connect (/usr/local/src/ACS/node_modules/aerospike/lib/client.js:417:18)
    at Object.<anonymous> (/usr/local/src/ACS/con.js:26:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Here's the modification:
var gAs = require('aerospike');

var config = {
  	maxConnsPerNode: 1000
};

var as_client = gAs.client({
	hosts:[
		{addr: gCfg.dbhost, port: gCfg.dbport}
	],
	log: {
		level: gAs.log.INFO
	},
	policies: {
		timeout: 5000
	}
})

conn.conn = as_client.connect(config, function (err) {
	if ( !err ) {
		console.log("Connection to Aerospike cluster succeeded!");
	}
	else {
		console.log("Connection to Aerospike cluster failed!");
		console.log(err);
	}

});

**Comment by jhecking** [comment]
@lbabiera,

The `Aerospike.connect` function is a short-hand form for calling `client = Aerospike.client(config)` followed by  `client.connect(callback)`. If you use the latter method to initialize and connect the client, then you need to pass the `maxConnsPerNode` setting to the `Aerospike.client` method, just like the other configuration settings:

```
const Aerospike = require('aerospike')
var as_client = Aerospike.client({
  hosts: [{addr: gCfg.dbhost, port: gCfg.dbport}],
  log: { level: Aerospike.log.INFO },
  policies: { timeout: 5000 },
  maxConnsPerNode: 1000
})
as_client.connect(function (err) {
  if (!err) {
    console.log("Connection to Aerospike cluster succeeded!")
  } else {
    console.log("Connection to Aerospike cluster failed!")
    console.log(err)
  }
})
```

Please refer to the client's [API docs](http://www.aerospike.com/apidocs/nodejs/) for more details and examples.

**Comment by lbabiera** [comment]
Thanks for your help jhecking, I really appreciate it.

**Comment by NawarA** [comment]
@jhecking Can you please update the docs to include `maxConnsPerNode`? There is no info on them in the configuration.md file

**Comment by jhecking** [comment]
@NawarA, please refer to the notice at the top of `configuration.md`:

> This document covers the 1.x version of the Aerospike Node.js client. For the 2.0 client, please refer to the API documentation available at http://www.aerospike.com/apidocs/nodejs/.

Specifically, you want to look at [Config.html#maxConnsPerNode](http://www.aerospike.com/apidocs/nodejs/Config.html#maxConnsPerNode) for the v2.0 client.

**Comment by GavinDmello** [comment]
I'm getting this error for normal gets in 2.x. Is there an optimum value maxConnPerNode needs to be set to? Because the moment maxConsPerNode is exceeded, it throws this error.
Also, Would setting this to a high value affect the performance as process has to keep those many   connections open ?

**Comment by jhecking** [comment]
@GavinDmello, no, there is no optimal size for this setting. It depends on your specific setup. If you are running into this issue then you should try to increase the limit. As you note there is some overhead for managing more open connections per cluster node. Depending on how many clients you have that connect to the cluster you may also have to keep an eye on the max. number of open connections on the server.

**Comment by GavinDmello** [comment]
@jhecking Having so many connections open could be problem in a high concurrency environment. 
 Does it create a new connection per transaction ?

**Comment by jhecking** [comment]
The client creates a separate connection pool for every cluster node it connects to. `maxConnPerNode` is the upper limit for the number of connections per pool. The client does not create new connections for every transactions but reuses connections from the pool.

**Comment by GavinDmello** [comment]
@jhecking Okay. I did not get this issue in 1.x . It worked pretty well with the defaults.

**Comment by jhecking** [comment]
Please refer to my [earlier comment from May last year](#issuecomment-221228291) for a very brief discussion of the architectural differences between the v1 and v2 client. Basically, with v1 you have a natural throttling mechanism through the use of libuv's worker threads that limits how fast the client commands can be processed. With v2 there is no such limitation. That results in improved throughput and much reduced memory usage.

If you are hitting the `maxConnsPerNode` limit you have two options: Raise the limit or add a buffering mechanism if you only exceed the limit during relatively short periods of burst activity.

**Comment by NawarA** [comment]
@jhecking great write up btw! Very well written and great content

**Comment by jhecking** [comment]
Thanks, @NawarA!

**Comment by sandy10786** [comment]
@jhecking Great content and very helpful but I have one question regarding the issue.  I am facing the same issue but only with PUT operation. Just want to know whether it's expected in PUT operation or just coincidence. Also in client v2, if we are not using  libuv's worker then why number of async connections with event loop are exceeding as i am using global aerospike connnection for all my operation in service.

**Comment by jhecking** [comment]
@sandy10786, yes, it is expected that you would get this error (`AerospikeError: Max node/event loop [...] async connections would be exceeded: 300`) if you are trying to execute more transactions than the configured `maxConnsPerNode` limit (default: 300).

If you are running into this issue, I would recommend you update the client to at least v3.2 or later. In v3.2, we added a new, optional command queue. Rather than throwing an error, the client will temporarily buffer the commands if you exceed the max. in-flight limit. This would be  a good solution, if you are exceeding the limit only occasionally, i.e. during short bursts. If you are constantly exceeding the limit, you need to raise the limit, as you will fill up the command queue quickly otherwise.

**Comment by sandy10786** [comment]
@jhecking Got it. Thanks for the reply.
