### ISSUE TITLE
Segmentation Fault - NodeJS v6.1.0 and AerospikeNodeJS v2.1.1

### ISSUE THREAD

**Issue by kinghadi** [aerospike/aerospike-client-nodejs#133]
**Problem**
I have `nodejs v6.1.0` and `Aerospike NodeJS v2.1.1` and when I try to put a user , I get a `Segmentation Fault`. What I tried are:
 - I removed `node_modules` and `npm install` again 
 - Running `npm rebuild`

But nothing worked! I call my aerospike code from my test.

We are using `redis` and we want to migrate to `aerospike` and I don't know that when these kind of problems show up to prevent.

**Code**
```
client.put(key, userProfile, function (err){
					if(err){
						throw err;
						next(err);
					}else{
						console.log("@Ping/AerospikeService: new userRecord wrote:", userProfile);
						next(null, "done "+ Aerospike.status.AEROSPIKE_ERR_RECORD_NOT_FOUND);
					}
				});
				break;
```

**Data**
My `userProfile` is a json object fetched from a `mongoDB`:
```
{ _id: 577626aafa6164f014ad1708,
  __v: 0,
  memberships: { groups: [], boards: [] },
  lastSeenSetting: { VIPList: [] },
  statusSetting: { VIPList: [] },
  pictureSetting: { VIPList: [] },
  profileSettings: { exclude: [] },
  sessionList: 
   [ { sessionToken: 'sessionTokenA-1',
       deviceName: 'DeviceNameA',
       lastLoginDate: 2016-07-01T08:15:38.076Z,
       ipAddress: '127.0.0.1',
       _id: 577626aafa6164f014ad1709 } ],
  info: 
   { id: 'userIdA',
     username: 'username',
     phoneNumber: '**********',
     profilePhotoList: [],
     status: { title: ':)) ', likes: 100 } },
  id: '577626aafa6164f014ad1708' }

```

**Comment by kinghadi** [comment]
It was working with small objects like the following: 
`
{
  field1: "hellooooo",
  field2: "goodbyeee"
}
`
but with the `userProfile` data it crashed.

**Comment by jhecking** [comment]
Hi @kinghadi,

Can you please post the error message that you are getting as well. Does the program crash every time you are trying to write a userProfile record or just occasionally or for specific records?

Also, you're example is not a valid JSON object. What are the values of the `_id` and `lastLoginDate` properties? Numbers, strings, a Date object? Note that you will not be able to persist a Date object in the database directly; you'll have to convert it to a string or integer representation first.

But in either case it shouldn't be a problem to write (and read) such a record using the Aerospike client. I am able to write and read your sample record after converting `_id` and `lastLoginDate` to strings.

**Comment by kinghadi** [comment]
> Hi @kinghadi

Hi :)

> Can you please post the error message that you are getting as well. Does the program crash every time you are trying to write a userProfile record or just occasionally or for specific records?

It is just `Segmentation fault` on the screen and it shut down the node server. 

> Also, you're example is not a valid JSON object. What are the values of the _id and lastLoginDate properties? Numbers, strings, a Date object? Note that you will not be able to persist a Date object in the database directly; you'll have to convert it to a string or integer representation first.

These(`_id`) are retrieve from mongodb with `mongoose`. 

> But in either case it shouldn't be a problem to write (and read) such a record using the Aerospike client. I am able to write and read your sample record after converting _id and lastLoginDate to strings.

OK I will check it out!

**Comment by jhecking** [comment]
@kinghadi,

Can you please include the [`segfault`](https://www.npmjs.com/package/segfault) module in your application and capture the stack trace it prints out when the segfault happens?

    npm install segfault

Then add this to your application:

    var Segfault = require('segfault');
    Segfault.registerHandler("/path/to/write/segfaults");

Also would be good to enable debug logging for the client:

    var config = { log: { level: Aerospike.log.DEBUG, file: "/path/to/write/logs" } }
    Aerospike.connect(config, (err, client) => { ... })

See the [API docs](http://www.aerospike.com/apidocs/nodejs/Config.html#log) for more information.

**Comment by kinghadi** [comment]
When I want to install `segfault` 
```
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
```

**Comment by jhecking** [comment]
My bad: I gave you the wrong package name: `segfault` is an older fork of the `segfault-handler` package. Please use that latter package instead - the interface is identical:

    var SegfaultHandler = require('segfault-handler');
    SegfaultHandler.registerHandler("crash.log");

**Comment by kinghadi** [comment]
I did it. But there is no `crash.log`. after segmentation.

My `aeropsike.log` is :

```
Jul 01 2016 15:43:11 GMT: DEBUG(19087) [conversions.cc:201] [config_from_jsobject] - Parsing global policies : Done
Jul 01 2016 15:43:11 GMT: DEBUG(19087) [client.cc:115] [New] - Aerospike object initialization : success
Jul 01 2016 15:43:11 GMT: DEBUG(19087) [cluster.cc:52] [Connect] - Connecting to Cluster: Success
Jul 01 2016 15:43:14 GMT: DEBUG(19087) [exists_async.cc:62] [ExistsAsync] - Sending async exists command

Jul 01 2016 15:43:14 GMT: DEBUG(19087) [async.cc:138] [async_record_listener] - Invoking JS callback function
```

I don't know maybe there is a problem with `mongoose` json object!!

**Comment by kinghadi** [comment]
When I copy the content of `userProfile` object from console and add it manually to my code. It works well. but when I do it when I fetch it from mongoose it crashes. Does this lib is sensitive to some kind of objects or field values?

**Comment by kinghadi** [comment]
I figure it out. If you are trying to store a `mongoose` data object after retrieving (I mean through `find` or other queries) you have to call `.toJSON()` on the object.

**Comment by jhecking** [comment]
Great that you found a solution!

However, it's unacceptable that the client generates a segfault, regardless of the record object being passed. It should return a regular error object in the callback function instead.

So I setup Mongo and mongoose to try to replicate the issue with a simplified test case. I created a simple document schema, created a new document for it, saved it to MongoDB using mongoose and read it back. The resulting JS object is much more complex than a simple JSON representation of the document. In fact, the actual document is stored in a `_doc` property in the object. But there are lots of other properties as well.

Trying to store this Mondo model object into an Aerospike DB as is, resulted in various errors, due to unsupported Boolean or `undefined` property values and property names exceeding the max. bin name length (14). However I was not able to trigger a segfault, even after disabling a lot of the checks in the client code that guard against the previously encountered errors.

**Comment by jhecking** [comment]
For future reference, here is a copy of the test script I used: https://gist.github.com/jhecking/d67e94162e4a1e2b1cfc3556700f9f8f
