### ISSUE TITLE
Callback on changes to AS server

### ISSUE THREAD

**Issue by kinghadi** [aerospike/aerospike-client-nodejs#135]
is there any way of setting callback for changes that are made to a specific namespace ?

**Comment by jhecking** [comment]
Hi @kinghadi,

Aerospike Server does not support functionality like this at the moment.

The best you can do is to use the info command to periodically query stats about the namespace/set you are interested in, and to try to use the results to determine if any (relevant) changes have occurred. E.g. if you are only interested to find out if new records have been added to a given set, you could send the `sets/<ns>/<set>` info command to retrieve the total number of objects in the set and check for increases in that number. (Assuming you only ever create new records and don't delete records.)

    > client.info('sets/test/info', (err, info) => console.log(info))
    sets/test/info	n_objects=23:n-bytes-memory=442:stop-writes-count=0:set-enable-xdr=use-default:disable-eviction=false:set-delete=false;
    > client.put(new as.Key('test', 'info', 'foo'), {foo: "bar"}, (err) => {})
    > client.info('sets/test/info', (err, info) => console.log(info))
    sets/test/info	n_objects=24:n-bytes-memory=458:stop-writes-count=0:set-enable-xdr=use-default:disable-eviction=false:set-delete=false

YMMV depending on your specific requirements.

**Comment by kinghadi** [comment]
Hmm, I have to do some kind of polling. Ok thank you :)
