### ISSUE TITLE
Installation link for debian6 does not work

### ISSUE THREAD

**Issue by XEuRoMAN** [aerospike/aerospike-client-nodejs#137]
I can not install aerospike client via NPM because link which is generated here:
https://github.com/aerospike/aerospike-client-nodejs/blob/173497dfaa889a0114eed8748eef0152846160aa/scripts/aerospike-client-c.sh#L183
does not work when `${PKG_DIST}` is `debian6`

try it yourself:
http://www.aerospike.com/download/client/c/4.0.6/artifact/debian6

some logs form npm:
```
info: downloading 'http://www.aerospike.com/download/client/c/4.0.6/artifact/debian6' to '/node/system/node_modules/aerospike/aerospike-client-c/package/aerospike-client-c.tgz'
--2016-07-21 11:44:18--  http://www.aerospike.com/download/client/c/4.0.6/artifact/debian6
Resolving www.aerospike.com... 52.9.92.246, 52.9.110.232
Connecting to www.aerospike.com|52.9.92.246|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.aerospike.com/cgi/artifact.php?/download/client/c/4.0.6/artifact/debian6 [following]
--2016-07-21 11:44:19--  http://www.aerospike.com/cgi/artifact.php?/download/client/c/4.0.6/artifact/debian6
Reusing existing connection to www.aerospike.com:80.
HTTP request sent, awaiting response... 404 Not Found
2016-07-21 11:44:19 ERROR 404: Not Found.

error: Unable to download package from 'http://www.aerospike.com/download/client/c/4.0.6/artifact/debian6'
make: *** [binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate] Error 1
```

**Comment by jhecking** [comment]
@XEuRoMAN, you are right. The Aerospike C client, which the Node.js client uses internally, stopped supporting Debian 6 earlier this year. Therefore the Node.js client no longer supports Debian 6 either. I will need to update the documentation.

I'm sorry if that's not the answer you wanted to hear. Is upgrading your OS an option for you? Debian 6 is no longer supported by the Debian team either, I think.
