### ISSUE TITLE
client doesn't install on Arch Linux

### ISSUE THREAD

**Issue by felixsanz** [aerospike/aerospike-client-nodejs#139]
What's the reason for the library not installing on Arch Linux? This is not a musl based distro as Alpine is.

**Comment by jhecking** [comment]
As stated in #117, the Aerospike Node.js client library depends on the Aerospike C client library. We only provide pre-compiled binary packages of the C client for certain platforms. On other platforms, like Arch Linux, you will first need to compile the C client library yourself.

Have you tried compiling [aerospike-client-c](https://github.com/aerospike/aerospike-client-c) on Arch Linux?

**Comment by felixsanz** [comment]
I didn't but how it's that going to help? I mean, even if i compile the client library, npm will fail to install the node library right?

**Comment by jhecking** [comment]
Once you have build the C client from source, you can use that binary when installing the Node.js client. This is documented in the readme under [C Client Resolution](https://github.com/aerospike/aerospike-client-nodejs#C-Client-Resolution).

**Comment by felixsanz** [comment]
@jhecking It doesn't seem to work or i'm doing something wrong

```
felixsanz@earth  ~/D/aero-client  ls -la .
total 52
drwxr-xr-x  3 felixsanz felixsanz  4096 ago  4 11:46 ./
drwxr-xr-x 20 felixsanz felixsanz  4096 ago  4 11:38 ../
drwxr-xr-x  6 felixsanz felixsanz  4096 ago  2 01:38 aerospike-client-c/
-rw-r--r--  1 felixsanz felixsanz 35336 ago  4 11:46 npm-debug.log
-rw-r--r--  1 felixsanz felixsanz   264 ago  4 11:39 package.json

 felixsanz@earth  ~/D/aero-client  npm install --save aerospike

> aerospike@2.2.0 install /home/felixsanz/Desktop/aero-client/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/home/felixsanz/Desktop/aero-client/node_modules/aerospike/build'
  TOUCH binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
which: no lsb_release in (/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/felixsanz/Desktop/aero-client/node_modules/aerospike/node_modules/.bin:/home/felixsanz/Desktop/aero-client/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
error:  is not supported.
make: *** [aerospike-client-c.target.mk:17: binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate] Error 1
rm binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
make: Leaving directory '/home/felixsanz/Desktop/aero-client/node_modules/aerospike/build'
```

For completeness:

```
 felixsanz@earth  ~/D/aero-client  ls -la aerospike-client-c/lib/libaerospike.a 
-rw-r--r-- 1 felixsanz felixsanz 5671138 ago  2 01:38 aerospike-client-c/lib/libaerospike.a
 
felixsanz@earth  ~/D/aero-client  ls -la aerospike-client-c/include/aerospike/aerospike.h
-rw-r--r-- 1 felixsanz felixsanz 8739 ago  2 01:38 aerospike-client-c/include/aerospike/aerospike.h
```

This is Arch Linux. The name doesn't appear because the script uses `lsb_release` and related tools, not available in Arch.

I also tried to put the folder on `./node_modules/aerospike/` but the same happens.

**Comment by jhecking** [comment]
@felixsanz, did you set the `PREFIX` and `AEROSPIKE_LUA_PATH` environment variables as per [Custom Search Path](https://github.com/aerospike/aerospike-client-nodejs#custom-search-path)? It looks like you just copied some files manually.

If the script finds the required files (`libaerospike.a`, `aerospike.h` as well as `aerospike.lua`) already exist on the local filesystem, it does not need to detect the OS to download the correct binary package.

**Comment by jhecking** [comment]
@felixsanz, have you been able to get the client working on Arch Linux by compiling the C client driver yourself? Can I close this issue?

**Comment by felixsanz** [comment]
Sorry for the late response! This was on my pending list but a bit below.

I took some time to review it and with both variables it works just fine. Thanks!

**Comment by jhecking** [comment]
Thanks for the feedback!
