### ISSUE TITLE
Bins deleting doesn't work in multiple operations

### ISSUE THREAD

**Issue by cheriksoft** [aerospike/aerospike-client-nodejs#142]
I'm doing multiple operations on the record, using client.operate() method. During this proccess, some bins have to be deleted. As known, you have to set bin value to null, to delete it, but when I'm trying to add to operations array something like 
`ops.push(Aerospike.operator.write(binName, null));`
I get an exception in client.operate() method
```
Aug 09 2016 05:48:05 GMT: ERROR(24241) [operations.cc:1306] [operations_from_jsarray] - invalid operation [0] - result: -1
{ [AerospikeError: Operations array invalid]
name: 'AerospikeError',
message: 'Operations array invalid',
code: -2,
func: 'OperateAsync',
file: '../src/main/client/operate_async.cc',
line: 59 }
```
Of course, when there are no "null-write" operations, they execute without any errors

**Comment by jhecking** [comment]
Fixed in 1ec478eee854d250295919b8d30e97e6c982f481.
