### ISSUE TITLE
Regression: v2.3.0 fails to install on Amazon Linux

### ISSUE THREAD

**Issue by jhecking** [aerospike/aerospike-client-nodejs#143]
Ref. https://github.com/aerospike/aerospike-client-nodejs/issues/92#issuecomment-239085186

**Comment by jhecking** [comment]
@ApsOps, v2.3.1 is available on npmjs.com now and should install on Amazon Linux. Please give it a try.

**Comment by ApsOps** [comment]
@jhecking Works! Kudos for the quick fix :)
