### ISSUE TITLE
On disconnect listener

### ISSUE THREAD

**Issue by GavinDmello** [aerospike/aerospike-client-nodejs#145]
Is there an on disconnect event which is emitted on the client ? I've seen the latest flag in version 2.x and checking the isConnected flag will require some processing which I don't think is favourable.

**Comment by jhecking** [comment]
No, the client object does not emit any events at the moment.

The [Client#isConnected](http://www.aerospike.com/apidocs/nodejs/Client.html#isConnected) does not do any processing. The cluster tend process is continuously happening in the background and enables the client to receive updates about cluster changes, e.g. new/removed nodes, etc. Any cluster node that does not respond to five consecutive tend requests is considered unconnected. `isConnected` returns true if any cluster node has successfully responded at least once to the last five cluster tend requests. But even if none of the cluster nodes responds, the client will keep trying to re-connect to the cluster indefinitely until `Client#close` is called explicitly.

**Comment by GavinDmello** [comment]
By processing I meant checking the isConnected result repeatedly  at my end. I just need a way in which my process is notified about the server going down.

**Comment by jhecking** [comment]
Sorry, there isn't currently any way to get notifications from the client object. I'll treat this as a feature request.

**Comment by rahulbhanushali** [comment]
Do we have any plans for implementing this feature in the near future?

**Comment by jhecking** [comment]
Not in the short term.

**Comment by MikeLeonard** [comment]
Hi just wanted to flag that I need this as well so it's a '+1' for the feature request. I have an app that that is putting things into aerospike. Currently the app waits until the node.js aerospike client has connected to at least one aerospike database which is great. However I would ideally want it to also know when it's not connected to any aerospike databases so that I can deal with this. Just thought I'd share my interest in the hope of increasing priority of the feature request :).

**Comment by jhecking** [comment]
Planning to add 3 types of events to the `Client` interface:

* `nodeAdded` - when the client discovers a new node was added to the cluster,
* `nodeRemoved` - when the client loses connections to a cluster node,
* `disconnected` - when the client is no longer connected to any cluster nodes.

This is pending some work on the Aerospike C client but should be ready in the near future.
