### ISSUE TITLE
Synchronous error callback in query command causes "unspecified" error in record stream

### ISSUE THREAD

**Issue by blaazetech** [aerospike/aerospike-client-nodejs#146]
In our test code we are using `AS.query` and on error it gives a complete halt of system.

```
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at RecordStream.emit (events.js:144:17)
    at /home/ec2-user/testcode/node_modules/aerospike/lib/query.js:315:14
    at Query.foreach (/home/ec2-user/testcode/node_modules/aerospike/lib/query.js:313:11)
    at async.parallel.datasearch (/home/ec2-user/testcode/webnew.js:2301:27)
    at /home/ec2-user/testcode/node_modules/async/dist/async.js:3671:13
    at replenish (/home/ec2-user/testcode/node_modules/async/dist/async.js:884:21)
    at iterateeCallback (/home/ec2-user/testcode/node_modules/async/dist/async.js:869:21)
    at /home/ec2-user/testcode/node_modules/async/dist/async.js:847:20
    at /home/ec2-user/testcode/node_modules/async/dist/async.js:3676:17
    at /home/ec2-user/testcode/node_modules/async/dist/async.js:339:31
```

**Comment by jhecking** [comment]
@blaazetech, can you please post the parts of your code where you setup and execute the query? You need to attach an error event handler to the stream in order to handle any errors that could occur during stream processing.

Example:

```js
const Aerospike = require('aerospike')
Aerospike.connect((error, client) => {
  if (error) throw error
  var query = client.query('test', 'demo')
  query.select('id', 'tags')
  query.where(Aerospike.filter.contains('tags', 'green', Aerospike.indexType.LIST))
  var stream = query.foreach()
  stream.on('error', (error) => {
    console.error(error)
    // handle error
  })
  stream.on('data', (record) => {
    console.info(record)
  })
  stream.on('end', () => {
    client.close()
  })
})
```

**Comment by blaazetech** [comment]
Here is the sample code.
```
var k=350;
var scan = aerospikeclient.query("testns", "testset");
scan.select('rangelow','rangehigh','data');
scan.where(aerospike.filter.range("rangelow", range_lb,range_ub));//range has some values with lower bound and upper bound
var stream = scan.foreach();
var dataselected='UNKNOWN';
var count=0;
stream.on('data', function(record,meta,key){
    if(k>=record.rangelow && k<=record.rangehigh)
    {
	    dataselected=record.data;
    }
    count++;
});
stream.on('error', function(error){
    // handle the error in case an error occured during the scan.
    console.log(error);
    callback(null,null);
});
stream.on('end', function(end){
    if(dataselected!='UNKNOWN'&&dataselected!=undefined&&dataselected!=null)
    {
	    //convert to array for sending
	    dataselected=dataselected.split(',');
    }
    else
    {
	    dataselected=[];
    }
    callback(null,dataselected);
});
```

**Comment by jhecking** [comment]
I'm not able to reproduce the issue you are seeing. When an error occurs during `Query.foreach()` it calls the even handler defined in `stream.on('error')` for me instead of raising the exception. That's also what I would expect to happen by looking at Node's `events.js` library. [1]

Just for debugging purposes, can you surround the whole section with a `try {} catch` block and print out the error that gets raised?

[1] https://github.com/nodejs/node/blob/v4.x/lib/events.js#L144

**Comment by blaazetech** [comment]
```
stream.on('error', function(error){
    // handle the error in case an error occured during the scan.
    console.log(error);
    callback(null,null);
});
```
I used the same above code, which obviously need to `console.log` the error on screen, and for which i got this

```
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at RecordStream.emit (events.js:144:17)
    at /home/ec2-user/testcode/node_modules/aerospike/lib/query.js:315:14
    at Query.foreach (/home/ec2-user/testcode/node_modules/aerospike/lib/query.js:313:11)
    at async.parallel.datasearch (/home/ec2-user/testcode/webnew.js:2301:27)
    at /home/ec2-user/testcode/node_modules/async/dist/async.js:3671:13
    at replenish (/home/ec2-user/testcode/node_modules/async/dist/async.js:884:21)
    at iterateeCallback (/home/ec2-user/testcode/node_modules/async/dist/async.js:869:21)
    at /home/ec2-user/testcode/node_modules/async/dist/async.js:847:20
    at /home/ec2-user/testcode/node_modules/async/dist/async.js:3676:17
    at /home/ec2-user/testcode/node_modules/async/dist/async.js:339:31
```

**Comment by jhecking** [comment]
Are you saying that error message gets logged by the `console.log` statement in your error handler? So does `callback(null, null)` get called or not?

I would expect the "Error: Uncaught, unspecified "error" event." error to only get thrown if there is no error handler attached to the event emitter (RecordStream). What I would like to know is the underlying error that only gets represented as `[object Object]` in your log. You should be able to get this via the `context` property of the error object as per: 

https://github.com/nodejs/node/blob/v4.x/lib/events.js#L144-L146

      var err = new Error('Uncaught, unspecified "error" event. (' + er + ')');
      err.context = er;
      throw err;

**Comment by blaazetech** [comment]
No, we don't get any `console.log` also, but what we observed is as we are using `forever.js,cluster.js` and `express.js` it automatically closes that worker thread and forks a new one. As we get reconnection to Aerospike cluster messages in logs. Something like this.
```

Connection to Aerospike cluster succeeded!

Listening on 80
```
This is even strange for us, as we are unable to analyze the error involved here.

**Comment by jhecking** [comment]
So your error handler does not get called and Node throws the error. That's why I was suggesting to wrap the whole query logic in a try-catch statement so that you have a chance to print out the error and it's context before the worker thread gets closed.

**Comment by jhecking** [comment]
@blaazetech, any further updates on this issue? Have you had a chance to capture the error so that we can get some more details on it's origin?

**Comment by blaazetech** [comment]
Ya we didn't able to regenerate the same issue but my analysis said it was happening due to overload on the batchGet, where we were calling 1024 keys at a time with having 100 concurrency requests, so seems like it got to worker died.

Once the worker dies, the following messages came into picture when we used old version of aerospike with our new logic of code, that is where we got to know this issue.
```
Oct 04 2016 10:28:33 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
Oct 04 2016 10:28:33 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
Oct 04 2016 10:28:33 GMT: ERROR(6516) [batch_get.cc:199] [execute] - Cluster Object is NULL, can't perform the operation
Oct 04 2016 10:28:33 GMT: ERROR(6516) [batch_get.cc:199] [execute] - Cluster Object is NULL, can't perform the operation
Oct 04 2016 10:28:33 GMT: ERROR(6516) [batch_get.cc:199] [execute] - Cluster Object is NULL, can't perform the operation
Oct 04 2016 10:28:33 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
Oct 04 2016 10:28:33 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
Oct 04 2016 10:28:33 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
Oct 04 2016 10:28:33 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
Oct 04 2016 10:28:34 GMT: ERROR(6516) [batch_get.cc:199] [execute] - Cluster Object is NULL, can't perform the operation
Oct 04 2016 10:28:34 GMT: ERROR(6516) [batch_get.cc:199] [execute] - Cluster Object is NULL, can't perform the operation
Oct 04 2016 10:28:34 GMT: ERROR(6516) [batch_get.cc:199] [execute] - Cluster Object is NULL, can't perform the operation
Oct 04 2016 10:28:34 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
Oct 04 2016 10:28:34 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
Oct 04 2016 10:28:34 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
Oct 04 2016 10:28:34 GMT: ERROR(6516) [get.cc:161] [execute] - Not connected to Cluster to perform the operation
```

Can you give any estimate on the maximum number of keys which we can pull from aerospike in a batchGet op.

**Comment by jhecking** [comment]
> Once the worker dies, the following messages came into picture when we used old version of aerospike with our new logic of code, that is where we got to know this issue.

What version of the client are you using? Based on your earlier sample code I assumed you are using v2.x; but these error messages suggest you are now using a v1.x client instead?

Regarding the batch requests: There is a configurable batch record limit on the server side; the default is 5000. There is no specific limit on the client side. In the v2 client there is a new `Client#batchRead` method which is much more efficient than the old `Client#batchGet` method in the v1 client.

**Comment by blaazetech** [comment]
Yes, in old version we were using `aerospike@1.0.54`

How batchRead differs from batchGet, will it become a stream, as the name suggests "Read".

**Comment by jhecking** [comment]
There are two main differences between batchRead and batchGet:

1) batchRead uses the newer Batch Index protocol, while batchGet uses the legacy Batch Direct protocol. You can read about the differences between the two protocols here: http://www.aerospike.com/docs/guide/batch.html#batch-index.
2) batchRead uses asynchronous I/O when communicating with the Aerospike server; batchGet uses synchronous, blocking I/O. In order to provide an async., callback-based API in the JS layer, the batchGet command uses libuv worker threads when communicating with the server. By default, Node.js only uses a worker pool of 4 threads so this can become a bottle neck. I went into a bit more details about the difference between synchronous and asynchronous I/O in a recent blog post, which you can find here: http://www.aerospike.com/blog/win-win-greater-speed-and-lower-latency-with-aerospikes-node-js-client-v2-0/.

I would recommend that you upgrade to the v2 as it might address they issues that you are seeing.

**Comment by blaazetech** [comment]
The problem we seen only after updating to v2 of client, i guess we need to try the `batchRead` once, if it solves our problem or not. Will update you soon about it.

**Comment by GavinDmello** [comment]
I'm doing something similar in 2.x and I'm getting this error 
```
      Error: Uncaught, unspecified "error" event. ([object Object])
       at RecordStream.emit (events.js:163:17)
       at aerospike/lib/query.js:315:14
       at Query.foreach (aerospike/lib/query.js:313:11)
       at Client.DefaultCallbackHandler [as callbackHandler] (aerospike/lib/client.js:74:12)
       at createIndexCb (aerospike/lib/client.js:550:12)
     context:
      { code: -7,
        message: 'Max node/event loop BB9DF528F565000 async connections would be exceeded: 1000',
        func: 'as_event_get_connection',
        file: 'src/main/aerospike/as_event.c',
        line: 404 } },
```
I tried bumping the maxConnsPerNode value, but it keeps failing at higher concurrency . We're doing a lot of querying

**Comment by jhecking** [comment]
Finally got to the bottom of this: If an error occurs before the C client can send a async database command to the socket, the callback will be called synchronously, before the async function call returns.

A simple test program can demonstrate this:

```js
const Aerospike = require('aerospike')
const assert = require('assert')

Aerospike.connect({ maxConnsPerNode: 0 }, function (err, client) {
  if (err) throw err
  var key = new Aerospike.Key('test', 'test', 'test')
  var syncCb = true
  client.put(key, {i: 1}, (err) => {
    assert(err.code === Aerospike.status.AEROSPIKE_ERR_NO_MORE_CONNECTIONS)
    assert(syncCb === false, 'Callback was called synchronously!')
    client.close()
  })
  syncCb = false
})
```

In the case of query/scan commands a synchronous callback can cause an error to be emitted by the query/scan record stream before an error handler has been attached to the stream. In that case Node.js will raise the "unspecified" error.

I'm working on a fix for the Node.js client to detect when a synchronous error callback by the C client happens and to ensure the JS callback happens asynchronously even in that case.

**Comment by GavinDmello** [comment]
@jhecking I think the.error is emitted before the error listener is registered. Luckily, The query.excute function takes a error callback which doesn't crash my app now

**Comment by jhecking** [comment]
> I think the error is emitted before the error listener is registered.

Yes, that is exactly what is happening in the case of the "unspecified" errors. It just wasn't clear to me why this was happening due to a misconception about the nature of the async C client callbacks.

> Luckily, The query.excute function takes a error callback which doesn't crash my app now

Yes, that is a possible work-around until I can release a fixed client. Although it is not documented, the [`Query#foreach`](http://www.aerospike.com/apidocs/nodejs/Query.html#foreach__anchor) and [`Scan#foreach`](http://www.aerospike.com/apidocs/nodejs/Scan.html#foreach__anchor) methods take three callback functions as parameters which will be attached as data/error/end handlers to the record stream before the query gets executed:

```js
Query.prototype.foreach = function (policy, dataCb, errorCb, endCb) {
  var stream = new RecordStream(this.client)
  if (dataCb) stream.on('data', dataCb)
  if (errorCb) stream.on('error', errorCb)
  if (endCb) stream.on('end', endCb)
  // ...
})
```

**Comment by GavinDmello** [comment]
For the stream,  You can emit the error on the next tick if it solves the problem.

**Comment by jhecking** [comment]
That's more or less what I'm doing in #188.

**Comment by GavinDmello** [comment]
Great 👍
