### ISSUE TITLE
Aerospike.operator.write doesn't update double value

### ISSUE THREAD

**Issue by OlegPoberegets** [aerospike/aerospike-client-nodejs#148]
`let key = { "ns":  Config.aerospike.Namespace, "set": Config.aerospike.setWin, "key": hash };
let record = {
	"hash": hash,
	"time": timestamp,
	"win": 0,
	"winprice": 0,
};
let metadata = { "gen": 1, "ttl": Config.aerospike.ttl }; 
client_aerospike.put(key, record, metadata, (error) => {
	if (error) console.error('Error Set Bid Request Aerospike DB', error);
});
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

let keyReport = { "ns":  Config.aerospike.Namespace, "set": Config.aerospike.setWint, "key": hash };
let op = Aerospike.operator;
let ops = [
    op.write('win', 1),
    op.write('winprice', winbid) // **winbid === 1.21**
];
client_aerospike.operate(keyReport, ops, {}, {}, (error, record) => {});`

Method Aerospike.operator.write rounds value to integer. In my case bid 'winprice' **will equal 1**.

**Comment by jhecking** [comment]
@OlegPoberegets, you are right, `Aerospike.operator.write` does not support double values currently. A fix will be included in the next release.

**Comment by OlegPoberegets** [comment]
@jhecking, thank you for your work.
