### ISSUE TITLE
If I set array or object as argument in UDF then I can't work with them like with Lua table type. 

### ISSUE THREAD

**Issue by OlegPoberegets** [aerospike/aerospike-client-nodejs#150]
`const query = client.query(namespace, set);
query.where(aerospike.filter.range('time', 1476102547 - 1000000, 1476102547+1000000));

query.setUdf('sample', 'my_query', [{ "filter": [{
		"field": 'type',
		"value": 'banner',
		"type": 'equal'
	}]
}]);`

**sample.lua**
`function my_query(stream, arguments)
end
`

I can get properties from `arguments` like `arguments["filter"]` but I can't iterate over `arguments` or `arguments["filter"]` because Lua functions `pairs` and `ipairs` throw error - "table expected, got userdata"

**Comment by jhecking** [comment]
The object in the arguments list is not passed as a table but as an instance of the `Map` class, which is described here: http://www.aerospike.com/docs/udf/api/map.html. So you need to use the `map.pairs()` method to iterate the key/value pairs.
