### ISSUE TITLE
touch operation

### ISSUE THREAD

**Issue by GavinDmello** [aerospike/aerospike-client-nodejs#151]
Is operate.touch supposed to reset the TTL to the default TTL or update the TTL. There is a parameter called TTL to the function but it's not being honoured in any way, unfortunately and the TTL gets reset to the default TTL.

**Comment by GavinDmello** [comment]
Just figured out the issue is in 1.x and has been solved in 2.x. The touch operation in 1.x takes two params when it should take only one.

**Comment by jhecking** [comment]
The `ttl` param from the `touch` operation is being used to set the TTL here: https://github.com/aerospike/aerospike-client-nodejs/blob/maint/1.0/src/main/util/conversions.cc#L2392. There is a test case covering the touch operation as well which works as expected for me: https://github.com/aerospike/aerospike-client-nodejs/blob/maint/1.0/test/operate.js#L186.

Can you show an example usage of the `touch` operation which doesn't work?

As an aside, is there a specific reason you are still using v1.x and cannot upgrade to v2.x?

**Comment by GavinDmello** [comment]
You can try it with this snippet. It refreshes the TTL but to the default ttl value, which in our case was 43200 which is 5 days. It does not reset it to the value provided in 1.x

```js
var aerospike = require('aerospike');

var status = aerospike.status;
var op = aerospike.operator


var id = "three"
var revkey = aerospike.key(
    "test",
    "test",
    id
);

var bins = {
    name: id
}

var meta = {
    ttl: 30
}

var client = aerospike.client({
    hosts: [{
        "addr": '127.0.0.1', // Change this to your own ip while running inside docker.
        "port": 3000
    }]
})

function connect(callback) {
    client.connect(function(err) {
        if (err && err.code !== status.AEROSPIKE_OK) {
            console.log("failed to connect")
            console.log(err)

            callback(err)
        } else {
            console.log("connected")
            callback(null)
        }
    });

}



function createRecord() {
    client.put(
        revkey, 
        bins,
        meta,
        {},
        function(err, result) {
            console.log(err)
            console.log(result)
    });
}

function updateRecord() {
    var ops = [
        op.touch(30)
    ]

    client.operate(
        revkey,
        ops,
        function (err, rec, meta) {
            console.log(err)
            console.log(rec)
            console.log(meta)

        }
    )
}

console.log(process.argv)
console.log(process.argv[2])

connect(function (err) {
    if (err) {
        console.log('failed', err)
    } else {
        if (process.argv[2]== "1") {
            console.log("creating")
            createRecord()
    } else {
        console.log("updating")
        updateRecord()
    }

    }

})
```

Also, notice `https://github.com/aerospike/aerospike-client-nodejs/blob/maint/1.0/lib/aerospike.js#L343` takes 2 parameters where the second parameter is the ttl which is bug according me .
We're on course to moving towards 2.x , but right now there are a few breaking changes which will need some changes at our end and our code is already in production.
Example The err  in the callbacks used to provide codes no matter if there was an error or not and 2.x they have been replaced by null. Also, the deprecation of batch functions . I know those are back word compatible but we have to still change to batchRead and it will take some time.

**Comment by jhecking** [comment]
I see what you mean now: The first `bin` parameter in the touch function is indeed superfluous and should be removed. The touch operation does work if you pass in some (any) value for `bin`, e.g.

    var ops = [
        op.touch(null, 30)
    ]

Would that be acceptable as a work-around for you? I wasn't planning on doing any more releases for the 1.x client.

**Comment by GavinDmello** [comment]
You could change it and not make a release, `Just a suggestion`. It would be helpful for anyone who's still on 1.x

**Comment by jhecking** [comment]
Please send a PR and I will merge it.

**Comment by GavinDmello** [comment]
Done.

**Comment by jhecking** [comment]
Thanks! Merged.
