### ISSUE TITLE
Ubuntu 17.04: npm install aerospike fails to download C client

### ISSUE THREAD

**Issue by kitex** [aerospike/aerospike-client-nodejs#154]
Aerospike nodejs client install in Ubuntu16.10 is generating url for ubuntu16.04.

After update and upgrade to ubuntu17 :

aerospike@2.4.1 install /opt/projects/amatyastore/node_modules/aerospike
node-gyp rebuild
> make: Entering directory '/opt/projects/amatyastore/node_modules/aerospike/build'
>   TOUCH binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
>   ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
> info: downloading 'http://artifacts.aerospike.com/aerospike-client-c/4.1.1/aerospike-client-c-libuv-devel-4.1.1.ubuntu17.04.x86_64.deb' to '/opt/projects

**Comment by jhecking** [comment]
I'll fix this in the next release which I'm working on right now.
