### ISSUE TITLE
Remove TLS config support

### ISSUE THREAD

**Issue by jhecking** [aerospike/aerospike-client-nodejs#160]
Preliminary support for TLS was added in v2.4.0 but was never functional. As it turns out, the Aerospike C client library does not currently support TLS encryption when used in async mode with libuv, since libuv does not support TLS streams natively.

**Comment by felixsanz** [comment]
@jhecking So it's not possible to use http://www.aerospike.com/docs/guide/security/tls.html ?

**Comment by jhecking** [comment]
Unfortunately, TLS is not supported by the Node.js client at the moment. The problem is that libuv does not support TLS and therefore our Aerospike C client doesn't support TLS in async mode with libuv.

It doesn't look like libuv is going to support TLS any time soon either:
https://github.com/libuv/libuv/issues/100
https://github.com/libuv/libuv/issues/1128

**Comment by felixsanz** [comment]
So how to secure the cluster? It is possible to config the cluster in a way that only some specified IPs are able to join the cluster?

**Comment by jhecking** [comment]
The client does support [access control](http://www.aerospike.com/docs/guide/security/access-control.html). The server does not support IP based whitelists but that can be done using a firewall on the host or network.

If TLS encryption is a requirement then [stunnel](https://www.stunnel.org/) might be a feasible work-around until the client can natively support it.
