### ISSUE TITLE
Cannot install aerospike with npm

### ISSUE THREAD

**Issue by zhassanbey** [aerospike/aerospike-client-nodejs#161]
Hi there! I am trying to install aerospike nodejs client by 'npm install aerospike'. But I get errors:

> /bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
aerospike.target.mk:186: recipe for target 'Release/obj.target/aerospike.node' failed
make: *** [Release/obj.target/aerospike.node] Error 1
rm binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
make: Leaving directory '/home/zhassan/Projects/facebooksearchasynch/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.7-300.fc23.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zhassan/Projects/facebooksearchasynch/node_modules/aerospike
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/zhassan/Projects/facebooksearchasynch/package.json'
npm WARN facebooksearchasynch No description
npm WARN facebooksearchasynch No repository field.
npm WARN facebooksearchasynch No README data
npm WARN facebooksearchasynch No license field.
npm ERR! Linux 4.4.7-300.fc23.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "aerospike"
npm ERR! node v6.2.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! aerospike@2.4.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@2.4.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aerospike
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/zhassan/Projects/facebooksearchasynch/npm-debug.log

I am working on Linux/Fedora 23. Node js version 6.2.1, npm version 4.0.5
I tried to:
* remove ~/.node-gyp package first
* install node-gyp
* restart computer

How could I resolve that issue? Thanks in advance

**Comment by jhecking** [comment]
> /bin/ld: cannot find -lz

It looks like you are missing `libz` on your system. Try `yum install zlib`, then reinstall the package.

**Comment by jhecking** [comment]
Also make sure you have the other dependencies installed: https://github.com/aerospike/aerospike-client-nodejs#centosrhel-6

**Comment by jhecking** [comment]
Closing this issue. Please reopen if you are still having issues.
