### ISSUE TITLE
Durable delete - documentation missing

### ISSUE THREAD

**Issue by rahulbhanushali** [aerospike/aerospike-client-nodejs#164]
How do we use the durable delete feature with the nodejs client?

The release notes for 2.4.0 says, the provision for durable delete has been added but couldn't find anything regarding it in the API documentation.

**Comment by jhecking** [comment]
You are right, this new feature needs to be documented in the client API docs. Will do!

There is one test that shows how the feature is used here: https://github.com/aerospike/aerospike-client-nodejs/blob/master/test/remove.js#L138

    var policy = {
      durableDelete: true
    }
    client.remove(key, policy, function (err) { ... })
