### ISSUE TITLE
Update os_version script to support LinuxMint 18.1

### ISSUE THREAD

**Issue by jhecking** [aerospike/aerospike-client-nodejs#166]
In LinuxMint 18.1, the contents of `/etc/os-release` changed from using `ID=ubuntu` to `ID=linuxmint`. An additional field `ID_LIKE=ubuntu` was added:

    NAME="Linux Mint"
    VERSION="18.1 (Serena)"
    ID=linuxmint
    ID_LIKE=ubuntu
    PRETTY_NAME="Linux Mint 18.1"
    VERSION_ID="18.1"
    HOME_URL="http://www.linuxmint.com/"
    SUPPORT_URL="http://forums.linuxmint.com/"
    BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
    VERSION_CODENAME=serena
    UBUNTU_CODENAME=xenial

Source: https://github.com/zyga/os-release-zoo/blob/master/linuxmint/linuxmint-18.1.txt

`ID_LIKE` can be used as a fallback if `ID` is not supported. Challenge: How to determine the equivalent version number of the "like" distribution? E.g. is LinuxMint 18.1 based on Ubuntu 14.04 or Ubuntu 16.04? (It's the latter, but we are not able to determine that from the information in `os-release`.)

**Comment by evalsocket** [comment]
Can we go with trial and error method with both version.

**Comment by jhecking** [comment]
I'm not sure what you mean by "trial and error method" - can you please elaborate?

**Comment by evalsocket** [comment]
I think you can go with 16.04 
Ref : http://blog.linuxmint.com/?p=3145
