### ISSUE TITLE
Cannot connect to client

### ISSUE THREAD

**Issue by abhinavzspace** [aerospike/aerospike-client-nodejs#168]
node versions tried: 6.10 and 7.7
OS: Mac OS 10.11.6

I am getting the following error while trying to connect using the following code

```
client.connect(function (error) {
  if (error) {
    // handle failure
    console.log('Connection to Aerospike cluster failed!', error)
  } else {
    // handle success
    console.log('Connection to Aerospike cluster succeeded!')
  }
})
```

Error:
```
Connection to Aerospike cluster failed! { AerospikeError: Failed to connect
    at Function.AerospikeError.fromASError (/Users/abhinav/projects/docri0/prosemirror/node_modules/aerospike/lib/aerospike_error.js:113:10)
    at Client.DefaultCallbackHandler [as callbackHandler] (/Users/abhinav/projects/docri0/prosemirror/node_modules/aerospike/lib/client.js:71:72)
    at connectCb (/Users/abhinav/projects/docri0/prosemirror/node_modules/aerospike/lib/client.js:427:10)
    at Client.connect (/Users/abhinav/projects/docri0/prosemirror/node_modules/aerospike/lib/client.js:420:18)
    at Object.<anonymous> (/Users/abhinav/projects/docri0/prosemirror/collab/aerospike.js:18:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/abhinav/projects/docri0/prosemirror/collab/server/instance.js:6:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
  name: 'AerospikeError',
  message: 'Failed to connect',
  code: -1,
  func: 'as_cluster_seed_nodes',
  file: 'src/main/aerospike/as_cluster.c',
  line: 375 }
```

I am able successfully go to `http://localhost:8081/#dashboard/127.0.0.1:3000`

**Comment by abhinavzspace** [comment]
There was probably some installation issue. Now while using [docker image](https://github.com/aerospike/aerospike-server.docker), problem solved.

**Comment by evalsocket** [comment]
Where is your config

**Comment by AshuPari** [comment]
I got the same error, what I have to do ??

**Comment by AshuPari** [comment]
please help I'm struck

**Comment by helipilot50** [comment]
You need to pass in a 'config' to tell the connect method where to find the Aerospike cluster. See http://www.aerospike.com/docs/client/nodejs

I use a function like this

const openAerospike = async function() {

	if (asClient)
		return(asClient);

	try {
		asClient = await aerospike.connect(asConfig.cluster) ;
		return asClient;
	} catch (err) {
		let errorMessage = `Failed to connect to Aerospike at ${asConfig.cluster.hosts} - ${err}`;
		logger.error(errorMessage);
		throw new Error(errorMessage);
	}
};


Where asConfig.cluster is the following:

cluster: {
    hosts: [
      { addr: '10.8.84.85', port: 3000 },
      { addr: '10.8.84.87', port: 3000 },
      { addr: '10.8.84.86', port: 3000 },
      { addr: '10.8.84.88', port: 3000 }
    ],
    connTimeoutMs: 1000
  }

**Comment by AshuPari** [comment]
Done the same thing again getting same error

**Comment by AshuPari** [comment]
I'm connecting aerospike 20times using nodejs client on that time I'm getting that error

**Comment by jhecking** [comment]
@AshuPari, can you share the relevant parts of your code with us so we can see exactly how you are configuring the client and calling [`Aerospike.connect`](https://www.aerospike.com/apidocs/nodejs/module-aerospike.html#.connect)?

Are you connecting 20 different client instances to the server and all are getting the same error? Or only one of them?

**Comment by AshuPari** [comment]
getting this error
15:13:41 PM [error] Error { AerospikeError: Failed to connect
6|vertica- | at Object.client.getProdServerConnection_152 (/home/tech/processes/vertica-domain-distribution/connectors/connector-aerospike-js/connection/client.js:34:16)
6|vertica- | at Module._compile (module.js:641:30)
6|vertica- | name: 'AerospikeError',
6|vertica- | message: 'Failed to connect',
6|vertica- | code: -1,
6|vertica- | func: 'as_cluster_seed_nodes',
6|vertica- | file: 'src/main/aerospike/as_cluster.c',
6|vertica- | line: 375 } (in /home/tech/processes/vertica-domain-distribution/connectors/connector-aerospike-js/connection/connection.js:74)
6|vertica- | (in /home/tech/processes/vertica-domain-distribution/master.js:213

**Comment by AshuPari** [comment]
using batchread function nodejs client

**Comment by jhecking** [comment]
@AshuPari, can you share with us the code in `getProdServerConnection` where you configure the client and try to connect? The two most likely reasons for this error are:

1. You are not configuring the client correctly, i.e. you are not passing the address/port of at least one seed node. There are several ways to do so. Please refer to this [brief tutorial](https://www.aerospike.com/apidocs/nodejs/tutorial-getting_started.html).
2. The client is not able to connect to the address/port you specified, because of network issues, a firewall that blocks the connection, etc. Can you check whether you can connect to the specified address/port from the machine where the client is running, e.g. using telnet, nc, etc.?

**Comment by AshuPari** [comment]
prodServerCluster: {
        username: "",
        password: "",
        hosts: [
            {addr: 103.##.##.##.##, port: 3000}
        ],
        log: {
            level: Aerospike.log.INFO
        },
        policies: {
            timeout: 50000
        },
        maxConnsPerNode: 200000
    }

**Comment by AshuPari** [comment]
there is no connection problem

**Comment by jhecking** [comment]
@AshuPari,

It might not be relevant to your issue, but to set a username, when connection to the cluster, you would have to set [`Config.user`](https://www.aerospike.com/apidocs/nodejs/Config.html#user), not `username`.

Also, as of client version 3.0, `policies: { timeout: 50000 }` is not the correct way to set a global timeout any more. Please refer to [this document](https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/api-changes.md#policy-changes-improved-timeout--retry-handling) about the improved timeout & retry handling in client v3.0 or later. (Unless you are still on an older v2.x version, in which case I would recommend updating your client.)

Do you have the [Aerospike command line tools](https://www.aerospike.com/download/tools/3.15.2.1/) installed on your client machines by any chance? If yes, can you connect to the cluster using the `aql` or `asinfo` commands?

**Comment by AshuPari** [comment]
I'm connecting through aql

**Comment by jhecking** [comment]
@AshuPari,

Can you please enable debug logging for the embedded C client, by calling

    Aerospike.setDefaultLogging({ level: Aerospike.log.DEBUG })

before you try to connect the client. Then please check your log files for any error messages, esp. from `as_cluster_seed_nodes`, e.g. something like this:

    Feb 28 2018 08:30:03 UTC: WARN (3687) [as_cluster.c:235] [as_cluster_seed_nodes] - Failed to connect to seed 192.168.33.10 3333. AEROSPIKE_ERR_CONNECTION Socket write error: 32, 192.168.33.10:3333
