### ISSUE TITLE
npm install error on Elementary OS (Ubuntu based)

### ISSUE THREAD

**Issue by gmchaturvedi1** [aerospike/aerospike-client-nodejs#170]
Dea Team,

i am new aerospike when i installing module as instructed in ubuntu the following error is coming ,kindly suggest : 

gmchaturvedi@gmchaturvedi-HP-14-Notebook-PC:~/Documents/d/d1/Apps/client$ npm install aerospike

> aerospike@2.4.4 install /home/gmchaturvedi/Documents/d/d1/Apps/client/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/home/gmchaturvedi/Documents/d/d1/Apps/client/node_modules/aerospike/build'
  TOUCH binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
info: downloading 'https://artifacts.aerospike.com/aerospike-client-c/4.1.1/aerospike-client-c-libuv-devel-4.1.1-1.elementary0.4.x86_64.rpm' to '/home/gmchaturvedi/Documents/d/d1/Apps/client/node_modules/aerospike/aerospike-client-c/package/aerospike-client-c-libuv-devel-4.1.1-1.elementary0.4.x86_64.rpm'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 93220    0 93220    0     0   4717      0 --:--:--  0:00:19 --:--:-- 23665
scripts/aerospike-client-c.sh: line 70: [: ca69ba7be38bf3368ac5e64924de30a781d507de89a9481dbb31af21915d5c67: unary operator expected
error: invalid checksum for 'aerospike-client-c-libuv-devel-4.1.1-1.elementary0.4.x86_64.rpm'
aerospike-client-c.target.mk:16: recipe for target 'binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate' failed
make: *** [binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate] Error 1
rm binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
make: Leaving directory '/home/gmchaturvedi/Documents/d/d1/Apps/client/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-64-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gmchaturvedi/Documents/d/d1/Apps/client/node_modules/aerospike
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by jhecking** [comment]
This looks like an issue with the detection of the Linux distribution used. I'll need to update the build script to handle Elementary OS as a variant of Ubuntu.

**Comment by gmchaturvedi1** [comment]
ok thanx for your reply . So we need to wait till that .If it is possible then kindly tell us when can we updated so we can start using this .

**Comment by jhecking** [comment]
Only work-around would be to temporarily change `/etc/os-release` on your system(s) to set `ID` and `VERSION_ID` to those of Ubuntu, e.g.:

    ID="ubuntu"
    VERSION_ID="16.04"

The downside is that this change could potentially also affect other software that might use `/etc/os-release`. So it would be best to change this file back to it's original state once you have installed the npm package.

**Comment by gmchaturvedi1** [comment]
thanks for reply its done.Thanks for quick support.
