### ISSUE TITLE
i am using graphql can we async await call in query in aerospike

### ISSUE THREAD

**Issue by gmchaturvedi1** [aerospike/aerospike-client-nodejs#171]
i am using graphql when i use the follwing call:

const a =await client.get(k)

as i understand it return me a record but it returns me the following error : 
"\"callback\" argument must be a function",

but async await is for callback hell only.

**Comment by jhecking** [comment]
The [`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) operation expects to receive a `Promise` and waits until that promise gets resolved. The Aerospike Node.js client library does not currently support Promises and instead uses callbacks. Until Promise support is added to the library (#78) you might want to try the [Bluebird](http://bluebirdjs.com/) library to "promisify" the Aerospike client.
