### ISSUE TITLE
centos 6.8 error

### ISSUE THREAD

**Issue by gmchaturvedi1** [aerospike/aerospike-client-nodejs#182]
Dear team i am installing driver at centos 6.8 ,the following is coming kindly help me out over this : 

npm install aerospike --save

> webworker-threads@0.7.11 install /home/GM/linuxbackup/dev/Apps/server/node_modules/webworker-threads
> node-gyp rebuild

make: Entering directory `/home/GM/linuxbackup/dev/Apps/server/node_modules/webworker-threads/build'
  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
In file included from ../src/WebWorkerThreads.cc:12:
../node_modules/nan/nan.h:44:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from ../src/WebWorkerThreads.cc:5:
/root/.node-gyp/6.10.2/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.10.2/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/6.10.2/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/6.10.2/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/6.10.2/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/6.10.2/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: At global scope:
/root/.node-gyp/6.10.2/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.10.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/6.10.2/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/6.10.2/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/6.10.2/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: At global scope:
/root/.node-gyp/6.10.2/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.10.2/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/6.10.2/include/node/v8.h:3278: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: At global scope:
/root/.node-gyp/6.10.2/include/node/v8.h:4498: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h:4514: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/6.10.2/include/node/v8.h:7538: error: ‘nullptr’ was not declared in this scope
In file included from ../node_modules/nan/nan.h:191,
                 from ../src/WebWorkerThreads.cc:12:
../node_modules/nan/nan_maybe_43_inl.h: At global scope:
../node_modules/nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:29: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:37: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:45: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:52: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:71: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:79: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:87: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:96: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:105: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:115: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:125: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:141: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:149: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:155: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:164: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:171: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:179: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:186: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:194: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:202: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:210: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:226: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:234: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:244: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:254: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:266: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:277: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:284: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:290: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:296: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:302: error: expected initializer before ‘<’ token
../src/WebWorkerThreads.cc:935: error: expected ‘}’ at end of input
../node_modules/nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
make: Leaving directory `/home/GM/linuxbackup/dev/Apps/server/node_modules/webworker-threads/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-696.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/GM/linuxbackup/dev/Apps/server/node_modules/webworker-threads
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> aerospike@2.5.0 install /home/GM/linuxbackup/dev/Apps/server/node_modules/aerospike
> node-gyp rebuild

make: Entering directory `/home/GM/linuxbackup/dev/Apps/server/node_modules/aerospike/build'
  TOUCH binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
info: downloading 'https://artifacts.aerospike.com/aerospike-client-c/4.1.5/aerospike-client-c-libuv-devel-4.1.5-1.el6.x86_64.rpm' to '/home/GM/linuxbackup/dev/Apps/server/node_modules/aerospike/aerospike-client-c/package/aerospike-client-c-libuv-devel-4.1.5-1.el6.x86_64.rpm'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2273k  100 2273k    0     0   105k      0  0:00:21  0:00:21 --:--:--  106k
info: verifying checksum for 'aerospike-client-c-libuv-devel-4.1.5-1.el6.x86_64.rpm': OK
info: extracting files from 'aerospike-client-c-libuv-devel-4.1.5-1.el6.x86_64.rpm'

CHECK
   [✓] /home/GM/linuxbackup/dev/Apps/server/node_modules/aerospike/aerospike-client-c/package/usr/lib/libaerospike.a
   [✓] /home/GM/linuxbackup/dev/Apps/server/node_modules/aerospike/aerospike-client-c/package/usr/include/aerospike/aerospike.h
   [✓] /home/GM/linuxbackup/dev/Apps/server/node_modules/aerospike/aerospike-client-c/package/opt/aerospike/client/sys/udf/lua/aerospike.lua

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
In file included from ../src/include/client.h:23,
                 from ../src/main/aerospike.cc:17:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/.node-gyp/6.10.2/include/node/node.h:42,
                 from ../src/include/client.h:22,
                 from ../src/main/aerospike.cc:17:
/root/.node-gyp/6.10.2/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.10.2/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/6.10.2/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/6.10.2/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/6.10.2/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/6.10.2/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: At global scope:
/root/.node-gyp/6.10.2/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.10.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/6.10.2/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/6.10.2/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/6.10.2/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: At global scope:
/root/.node-gyp/6.10.2/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.10.2/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/6.10.2/include/node/v8.h:3278: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: At global scope:
/root/.node-gyp/6.10.2/include/node/v8.h:4498: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h:4514: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.10.2/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/6.10.2/include/node/v8.h:7538: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:190,
                 from ../src/include/client.h:23,
                 from ../src/main/aerospike.cc:17:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:59: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:64: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:69: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:76: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:83: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:91: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:98: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:108: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:114: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:118: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:125: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:130: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:135: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:139: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:145: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:150: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:156: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:162: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:168: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:174: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:180: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:186: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:194: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:201: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:205: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:209: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:213: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:217: error: expected initializer before ‘<’ token
../src/main/aerospike.cc:101: error: expected ‘}’ at end of input
../../nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/aerospike/src/main/aerospike.o] Error 1
rm binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
make: Leaving directory `/home/GM/linuxbackup/dev/Apps/server/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-696.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/GM/linuxbackup/dev/Apps/server/node_modules/aerospike
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.11 (node_modules/webworker-threads):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 2.6.32-696.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "aerospike" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! aerospike@2.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@2.5.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aerospike
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/GM/linuxbackup/dev/Apps/server/npm-debug.log

regards
gmchaturvedi

**Comment by jhecking** [comment]
Please ensure you are using gcc-4.8 or later as pointed out in the Readme:

> Note: The gcc tool chain included in CentOS/RHEL 6.x is gcc-4.4. To build the Aerospike addon using Node.js v4 or later, gcc-4.8 or later is required. To update the gcc tool chain you can install a recent version of the Red Hat Developer Toolset or a compatible devtoolset version for CentOS.

**Comment by jhecking** [comment]
@gmchaturvedi1, have you been able to resolve the installation issue?

**Comment by gmchaturvedi1** [comment]
Sorry to delayed reply its done thanks for your support
