### ISSUE TITLE
Support for Creating Keys with Digest

### ISSUE THREAD

**Issue by rashidmayesaero** [aerospike/aerospike-client-nodejs#183]
Currently, when creating a Key object with a ns, set, and digest, the `key_from_jsobject` throws an error because the key is null. 

`[conversions.cc:1163] [key_from_jsobject] - The key value cannot be undefined`

If the user key is null, but the digest is non-null, `as_key_new_digest` could be used instead of `as_key_init`.

**Comment by jhecking** [comment]
@rashidmayesaero, the fix is included in [v2.5.1](https://github.com/aerospike/aerospike-client-nodejs/releases/v2.5.1) which is available on [npmjs.com](https://www.npmjs.com/package/aerospike) now.
