### ISSUE TITLE
append method not working properly

### ISSUE THREAD

**Issue by ethpran** [aerospike/aerospike-client-nodejs#184]
I have a method which looks like this:

```
function(lastName, firstName, candidateId, candidate, callback) {
		var lastNameKey = new Aerospike.Key(namespace, set, lastName);
		var bins = {firstName: firstName, candidateId: candidateId, basicData: candidate};
		client.exists(lastNameKey, function(error) {
		 	if (error && error.code === Aerospike.status.AEROSPIKE_ERR_RECORD_NOT_FOUND) {
			    client.put(lastNameKey, bins, function(error, key) {
			    	if (error) {
			    		callback(error);
			    	} else {
			    		callback(null, key);
			    	}
			    });
	  		} else if (error) {
			    callback(error);
		  	} else {
		  		bins = _.reduce(bins, function(arr, val, key) {
		  			var obj = {};
		  			obj[key] = val;
		  			arr.push(obj);
		  			return arr;
		  		}, []);
			    client.append(lastNameKey, bins, function(error, record, metadata, key) {
			    	if (error) {
			    		callback('Append error\n'+error+'\n');
			    	} else {
			    		callback(null, key);
			    	}
			    });
		  	}
		});
}
```

However, whenever it attempts the append in the final condition, I keep getting these errors:
Apr 08 2017 19:46:04 GMT: ERROR(12568) [conversions.cc:961] [extract_blob_from_jsobject] - The binary data is not of the type UnsignedBytes
Apr 08 2017 19:46:04 GMT: ERROR(12568) [operations.cc:1266] [operations_from_jsarray] - invalid operation [4] - result: -1
AerospikeError: Operations array invalid

I believe my call is correctly formed and uses the same keys and and value types as the bins which currently exist for the PK

**Comment by jhecking** [comment]
The `append` method you are using is meant for bins of type string or bytes. It's a shortcut for the scalar [append](http://www.aerospike.com/apidocs/nodejs/module-aerospike_operations.html#.append) operation. But it looks like your bin values are lists of strings. In that case you should use the [lists.append](http://www.aerospike.com/apidocs/nodejs/module-aerospike_lists.html#.append) operation.

Here is an example of how you might use it:

```js
const as = require('aerospike')
const lists = as.lists
as.connect((err, client) => {
  if (err) throw err
  var key = new as.Key('test', 'test', 'listAppendTest')
  var bins = {
    ids: [41, 42],
    names: ['joe', 'jerald']
  }
  client.put(key, bins, (err) => {
    if (err) throw err
    var ops = [
      lists.append('ids', 43),
      lists.append('names', 'john'),
    ]
    client.operate(key, ops, (err) => {
      if (err) throw err
      client.get(key, (err, record) => {
        if (err) throw err
        console.log(record)
        client.close()
      })
    })
  })
})
```

Running the example you can see that the new ID and name (43, "john") are appended to the list of existing values:

    $ node list_append.js
    { ids: [ 41, 42, 43 ], names: [ 'joe', 'jerald', 'john' ] }

**Comment by ethpran** [comment]
thanks. this was indeed my issue. didn't pay attention to the distinction between scalars and lists. thanks

**Comment by jhecking** [comment]
I have already clarified the documentation on this point.

**Comment by ethpran** [comment]
much appreciated. thanks
