### ISSUE TITLE
model of data

### ISSUE THREAD

**Issue by gmchaturvedi1** [aerospike/aerospike-client-nodejs#185]
dear team,

i need some help on modeling of data:

my data is following :  

```
    "questions": [
      {
   "question": "I can gain the Support and commitment of others",
   "flag": "",
   "isAnswered": "",
   "selectedOption": "",
   "category": "Personality Development",
   "answers": [
   {"label": "Strongly Agree",
   "point": 5},
   {"label": "Agree",
   "point": 4},
   {"label": "Neither Agree nor Disagree",
   "point": 3},
   {"label": "Disagree",
   "point": 2},
   {"label": "Strongly disagree",
   "point": 1}
 ]},
 {
   "question": "I am always full of energy",
   "flag": "",
   "isAnswered": "",
   "selectedOption": "",
   "category": "Personality Development",
   "answers": [
   {"label": "Strongly Agree",
   "point": 5},
   {"label": "Agree",
   "point": 4},
   {"label": "Neither Agree nor Disagree",
   "point": 3},
   {"label": "Disagree",
   "point": 2},
   {"label": "Strongly disagree",
   "point": 1}
 ]}
]
```

how to edit individual question. kindly suggest.

regards
gmchaturvedi

**Comment by jhecking** [comment]
This question might be better suited for our discussion forums - we have a section specifically on [data modeling](https://discuss.aerospike.com/c/how-developers-are-using-aerospike/data-modeling).

That said the simple example you provide is not really enough to provide you with good advice on how to model your data. You might need to provide a bit more information about your specific use case. E.g. it looks like you are modelling data for some sort of user survey. But it's not clear whether the data is just meant to model the survey form or also meant to capture the responses of the users taking the survey? There is an `isAnswered` flag so it looks like the latter. But then how do you plan to capture the actual answer provided by the user?

**Comment by jhecking** [comment]
Closing this issue. Please feel free to reopen if you have further questions.
