### ISSUE TITLE
None Error thrown if cluster nodes "go down"

### ISSUE THREAD

**Issue by sempi** [aerospike/aerospike-client-nodejs#193]
In certain situations when cluster nodes are shut down, none standard node.js errors may be thrown. 

This is undesirable as the community is moving toward using Promises which in turn mandates the use of Errors in rejected responses.

Short of supporting a Promise based interface, it would be highly preferable if any error is derived from a JavaScript Error.

**Comment by jhecking** [comment]
Can you elaborate on the "certain situations" in which this occurs? What are the non-standard errors that are being thrown and which client commands are throwing them?

The just released [v2.5.2](https://github.com/aerospike/aerospike-client-nodejs/releases/v2.5.2) contains two fixes for bugs that could cause behavior like what you are describing with query/scan operations. Except for these cases all errors returned by the client should be derived from `AerospikeError` which inherits from `Error`.

**Comment by jhecking** [comment]
Closing this for now. Feel free to reopen with additional information.
