### ISSUE TITLE
General availability of Predicate Filtering?

### ISSUE THREAD

**Issue by blaazetech** [aerospike/aerospike-client-nodejs#200]
I was looking into this http://www.aerospike.com/docs/guide/predicate.html and was interested in knowing when will the nodejs client of aerospike support this.

**Comment by jhecking** [comment]
There are currently no plans to expose the low-level predicate filter API in the Node.js client. Work is under way on a high-level, SQL-like API, which will be made available in all the clients. However, I don't have a firm timeline at the moment.

**Comment by blaazetech** [comment]
Thanks for the fast reply, eagerly waiting for the next release to come in availability.
