### ISSUE TITLE
aerospike artifacts certificate has expired. Unable to execute npm build

### ISSUE THREAD

**Issue by umangkedia** [aerospike/aerospike-client-nodejs#209]
Getting this error:

error: Unable to download package from 'https://artifacts.aerospike.com/aerospike-client-c/4.1.8/aerospike-client-c-libuv-devel-4.1.8.pkg'

curl: (60) SSL certificate problem: Invalid certificate chain

**Comment by jhecking** [comment]
On it. Thanks for letting me know!

**Comment by jhecking** [comment]
The cert has been updated.

**Comment by tomacco** [comment]
It has happened again! Certificate has expired and the build fails.

**Comment by jhecking** [comment]
Thanks! The cert has been renewed already.
