### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by KSDevTeam** [aerospike/aerospike-client-nodejs#212]
I've installed this into an existing project, running the project gives me the following;

node: symbol lookup error: /path/to/project/node_modules/aerospike/build/Release/aerospike.node: undefined symbol: as_event_set_external_loop_capacity

**Comment by jhecking** [comment]
What client version did you install?

Can you try removing "node_modules/aerospike" and reinstalling the module? Then please post the output of the "npm install" here.

**Comment by KSDevTeam** [comment]
Didn't specify a version, assuming npm would just grab the latest stable;
Please find attached
[result.txt](https://github.com/aerospike/aerospike-client-nodejs/files/1208124/result.txt)

**Comment by jhecking** [comment]
In most cases, the Node.js client downloads a matching version of the Aerospike C client library when running `npm install`. But in your case, the install script has detected an existing version of the C client installed in `/usr`:

    CHECK
       [✓] /usr/lib/libaerospike.a
       [✓] /usr/include/aerospike/aerospike.h

What version of the C client library do you have installed? Node.js client v2.7.2 requires the latest C client library v4.1.8.

**Comment by KSDevTeam** [comment]
Hi Jan,

Thanks for your time on this.

I installed from here;
http://www.aerospike.com/download/client/c/4.1.8/artifact/ubuntu16

Installed following this;
http://www.aerospike.com/docs/client/c/install/ubuntu16.html

and ran this code from the usage section;
https://github.com/aerospike/aerospike-client-nodejs

Still got the same.

**Comment by jhecking** [comment]
For use with the Node.js client, you need the C client library compiled with support for the libuv async event framework, i.e. `aerospike-client-c-libuv-{VERSION}.ubuntu16.04.x86_64.deb`.

If you only need the C client library for use with Node.js, I would recommend you uninstall the separate aerospike-client-c package and just run `npm install aerospike`. The installation script of the Node.js client will automatically fetch the right version of the C client library and install it locally, under `node_modules`. That way you are guaranteed to get matching versions of Node.js client and C client library that have been tested together.

**Comment by KSDevTeam** [comment]
Uninstalling the aerospike-client-c debs worked for me. Using npm to install the aerospike module has pulled in a c client as you predicted.
Thank you so much for your support.

Regards
Keith

**Comment by dmyadav** [comment]
DOWNLOAD=1 npm install aerospike
will help you to install aerospike client forcefully.
