### ISSUE TITLE
Support of replica in BatchPolicy

### ISSUE THREAD

**Issue by blaazetech** [aerospike/aerospike-client-nodejs#228]
hi @jhecking,

can you please confirm that we do have support for replica method in Batchpolicy, as i see there is support for replica in the Readpolicy, but the same is not listed in the Batchpolicy, am not sure either the support is not there or it is infact there but not written in docs.

**Comment by jhecking** [comment]
Batch commands currently do not support the replica policy.

I see that one of your colleagues has also filed a support ticket for this as well. We'll take this into consideration as a feature request and I'll close this issue for now.
