### ISSUE TITLE
Error installing on Windows 10

### ISSUE THREAD

**Issue by helipilot50** [aerospike/aerospike-client-nodejs#244]
An error occurs when installing on Windows 10 64bit:

103 error code EBADPLATFORM
104 error notsup Unsupported platform for aerospike@3.1.1: wanted {"os":"linux,darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
105 error notsup Valid OS:    linux,darwin
105 error notsup Valid Arch:  x64
105 error notsup Actual OS:   win32
105 error notsup Actual Arch: x64

Log file is attached:
[2018-02-06T18_32_42_580Z-debug.log](https://github.com/aerospike/aerospike-client-nodejs/files/1698514/2018-02-06T18_32_42_580Z-debug.log)

**Comment by jhecking** [comment]
Windows support has landed on master in #239 but I have not yet released a new package that includes these changes. For now, you will have to check out the aerospike-client-nodejs repo and install the package from there. I am planning to release a new package later this week.

**Comment by helipilot50** [comment]
great thanks

**Comment by jhecking** [comment]
Hi Peter, I have just published [aerospike@3.2.0](https://www.npmjs.com/package/aerospike) ([CHANGELOG](https://github.com/aerospike/aerospike-client-nodejs/blob/master/CHANGELOG.md#320---2018-02-08)); you should be able to install that version on Windows 10 64bit.

**Comment by helipilot50** [comment]
Outstanding!

Regards

Peter

...Sent from my iPad
