### ISSUE TITLE
API documentation is inaccessible

### ISSUE THREAD

**Issue by aknuds1** [aerospike/aerospike-client-nodejs#251]
It's not possible to access the API documentation, linked to from the README, the link gives a 403: https://www.aerospike.com/apidocs/nodejs.

**Comment by jhecking** [comment]
Thanks for reporting this. Our web site was recently migrated to new hardware and it seems the API docs went missing in the process. I have forwarded the issue to the team taking care of the site and will update this issue once the docs are back online. Sorry for the inconvenience!

**Comment by jhecking** [comment]
@aknuds1, the docs are back:

https://www.aerospike.com/apidocs/nodejs/

**Comment by aknuds1** [comment]
Thanks!
