### ISSUE TITLE
During the build errors occur

### ISSUE THREAD

**Issue by madzukas** [aerospike/aerospike-client-nodejs#256]
How to recreate issue:
Run PowerShell as an Administrator
Install Node.js NPM on Windows: http://blog.teamtreehouse.com/install-node-js-npm-windows
Create a directory and initialize node package:

md asTest
cd asTest
npm init

Take all the default answers (not important for the test)
Install the Aerospike build tools
npm install windows-build-tools 
Install the Aerospike Node.js client. It will download half the internet and run a CXX compile
npm install aerospike

During the build errors occur

121 verbose stack Error: aerospike@3.2.0 install: `node-gyp rebuild`
121 verbose stack Exit status 1
121 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\
index.js:285:16)
121 verbose stack     at emitTwo (events.js:126:13)
121 verbose stack     at EventEmitter.emit (events.js:214:7)
121 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\
lib\spawn.js:55:14)
121 verbose stack     at emitTwo (events.js:126:13)
121 verbose stack     at ChildProcess.emit (events.js:214:7)
121 verbose stack     at maybeClose (internal/child_process.js:925:16)
121 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
122 verbose pkgid aerospike@3.2.0
123 verbose cwd C:\Users\peter\aerospikeNodeTest
124 verbose Windows_NT 10.0.10240
125 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
"install" "aerospike"
126 verbose node v8.9.4
127 verbose npm  v5.6.0
128 error code ELIFECYCLE
129 error errno 1
130 error aerospike@3.2.0 install: `node-gyp rebuild`
130 error Exit status 1
131 error Failed at the aerospike@3.2.0 install script.
131 error This is probably not a problem with npm. There is likely additional logging output above.
132 verbose exit [ 1, true ]

**Comment by jhecking** [comment]
Unfortunately npm's debug log file does not capture any error messages that get printed to stdout during the compile process by node-gyp. So this excerpt from the log file is not very helpful. Can you please capture the full output from running "npm install aerospike" and post that as well, please?

**Comment by jhecking** [comment]
@madzukas, is this still an issue? If you are still seeing any errors during installation/compilation, I really need to see the full output from running "npm install aerospike" to diagnose further.

**Comment by jhecking** [comment]
Closing this. Feel free to reopen or to file a new issue if you are still facing problems with the client.
