### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by George3d6** [aerospike/aerospike-client-nodejs#257]
Running: npm i aerospike yeld the following compilation errors:

OUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
In file included from ../src/main/aerospike.cc:19:0:
../src/include/policy.h:28:31: error: 'as_policy_event' was not declared in this scope
 int eventpolicy_from_jsobject(as_policy_event* policy, v8::Local<v8::Object> obj, const LogInfo* log );
                               ^~~~~~~~~~~~~~~
../src/include/policy.h:28:31: note: suggested alternative: 'as_policy_gen'
 int eventpolicy_from_jsobject(as_policy_event* policy, v8::Local<v8::Object> obj, const LogInfo* log );
                               ^~~~~~~~~~~~~~~
                               as_policy_gen
../src/include/policy.h:28:78: error: expected primary-expression before 'obj'
 int eventpolicy_from_jsobject(as_policy_event* policy, v8::Local<v8::Object> obj, const LogInfo* log );
                                                                              ^~~
../src/include/policy.h:28:83: error: expected primary-expression before 'const'
 int eventpolicy_from_jsobject(as_policy_event* policy, v8::Local<v8::Object> obj, const LogInfo* log );
                                                                                   ^~~~~
../src/include/policy.h:28:102: warning: expression list treated as compound expression in initializer [-fpermissive]
 int eventpolicy_from_jsobject(as_policy_event* policy, v8::Local<v8::Object> obj, const LogInfo* log );
                                                                                                      ^
../src/main/aerospike.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE register_as_event_loop(Nan::NAN_METHOD_ARGS_TYPE)':
../src/main/aerospike.cc:46:2: error: 'as_policy_event' was not declared in this scope
  as_policy_event policy;
  ^~~~~~~~~~~~~~~
../src/main/aerospike.cc:46:2: note: suggested alternative: 'as_policy_gen'
  as_policy_event policy;
  ^~~~~~~~~~~~~~~
  as_policy_gen
../src/main/aerospike.cc:47:2: error: 'as_policy_event_init' was not declared in this scope
  as_policy_event_init(&policy);
  ^~~~~~~~~~~~~~~~~~~~
../src/main/aerospike.cc:47:2: note: suggested alternative: 'as_policy_query_init'
  as_policy_event_init(&policy);
  ^~~~~~~~~~~~~~~~~~~~
  as_policy_query_init
../src/main/aerospike.cc:48:69: error: 'eventpolicy_from_jsobject' cannot be used as a function
  eventpolicy_from_jsobject(&policy, info[0]->ToObject(), &g_log_info);
                                                                     ^
../src/main/aerospike.cc:52:21: error: 'as_set_external_event_loop' was not declared in this scope
  as_status status = as_set_external_event_loop(&err, &policy, uv_default_loop(), &loop);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/main/aerospike.cc:52:21: note: suggested alternative: 'register_as_event_loop'
  as_status status = as_set_external_event_loop(&err, &policy, uv_default_loop(), &loop);

I have the following compilers:
```
g++ (GCC) 7.3.0
clang version 5.0.1 (tags/RELEASE_501/final)
```

**Comment by jhecking** [comment]
Did you by any chance install one of the Aerospike C client packages on the same machine before? During installation of the Aerospike Node.js client npm package, the installation script checks in `/usr/include/aerospike` for an existing `aerospike.h` header file. If it finds a copy there, it does not download another copy of the C client SDK. It looks like in your case an older copy of the C client header files were found in `/usr/lib`.

**Comment by George3d6** [comment]
Hmh, I quite certain I don't have any headers in /usr/lib

I do indeed have /usr/include/aerospike/aerospike.h, however it's not particularly old, I installed the client today.

Do I need to force the library to download everything (including the header) due to version incompatibilities ?

**Comment by jhecking** [comment]
Sorry, I meant `/usr/include`, off course. `/usr/lib` contains the libaerospike.a binary. It might not be a version conflict. It could also be a conflict if you did not install the version of the C client library compiled with support for libuv.

In any case, I would recommend that you force the download of the matching C client SDK during installation of the Node.js client package, by setting the `DOWNLOAD` environment variable to `1`, e.g.

    $ DOWNLOAD=1 npm install aerospike

**Comment by jhecking** [comment]
Closing this. Feel free to reopen or to file a new issue if you are still facing problems with the client.
