### ISSUE TITLE
Ubuntu 18.04 install fails

### ISSUE THREAD

**Issue by NawarA** [aerospike/aerospike-client-nodejs#258]
@jhecking I'm trying to install on Ubuntu 18 and Node 10.x, yet I'm seeing the install both throw warnings and fail.

I noticed a patch for fixing the g++ warnings was merged into master. When can we expect this patch to be released? Will the latest version of master allow Ubuntu 18 and Node 10 to successfully install? 

Thanks for the help. Happy to provide error logs or anything else that would help

**Comment by jhecking** [comment]
On leave. Don't expect a release before the week of June 25.

Jan

**Comment by jhecking** [comment]
I have released v3.4.0 and I do not see any compiler warnings during installation on Ubuntu 18 any longer. Can you please test whether you still see any errors during installation on your system(s)?

**Comment by NawarA** [comment]
Thanks for releasing! :+1: hope vacation was nice :)

 Here are the errors I'm seeing on Ubuntu 18 LTS w/ Node 10.4.1

[npmoutput.txt](https://github.com/aerospike/aerospike-client-nodejs/files/2125180/npmoutput.txt)
[2018-06-21T20_08_17_214Z-debug.log](https://github.com/aerospike/aerospike-client-nodejs/files/2125181/2018-06-21T20_08_17_214Z-debug.log)

**Comment by jhecking** [comment]
> /usr/bin/x86_64-linux-gnu-ld: cannot find -lz

You need to install the libz compression library. On Ubuntu, just run

    sudo apt-get install zlib1g-dev

**Comment by NawarA** [comment]
Got it. It worked! 

I'm running a fresh version of Ubuntu 18 LTS. That library doesnt come preinstalled on the OS. Would it be fair to add it to list of prereq libraries needed to run on Ubuntu?

**Comment by jhecking** [comment]
Agree! Will update the readme.

Cheers,
Jan

**Comment by hiren-ganatra** [comment]
> Agree! Will update the readme. Cheers, Jan
> […](#)
> On 23 Jun 2018, at 5:03 AM, Nawar Alsafar ***@***.***> wrote: Got it. It worked! I'm running a fresh version of Ubuntu 18 LTS. That library doesnt come preinstalled on the OS. Would it be fair to add it to list of prereq libraries needed to run on Ubuntu? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Can you please add the instructions to install such packages , so developers can save a lot of time googling for the solution. Thanks.

**Comment by jhecking** [comment]
Thanks for the reminder! I have updated the prerequisites section now: f51a011

But note that when you try to install `libz-dev` on Ubuntu 18, apt-get installs `zlib1g-dev` anyway:

```
# apt-get install g++ libssl1.0.0 libssl-dev libz-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
...
```
