### ISSUE TITLE
npm listed as a dependency

### ISSUE THREAD

**Issue by ratheo** [aerospike/aerospike-client-nodejs#259]
Unlike earlier versions, version 3.3.0 lists npm as a dependency. This causes installation of a lot of unneeded node modules, and seems to be a mistake.

**Comment by jhecking** [comment]
Thanks, will fix this for the next release. Note sure how this happened in the first place as the [tagged revision of package.json](https://github.com/aerospike/aerospike-client-nodejs/blob/v3.3.0/package.json) does not list `npm` as a dependency.

**Comment by jhecking** [comment]
Fixed in v3.4.0: https://www.npmjs.com/package/aerospike/v/3.4.0?activeTab=dependencies
