### ISSUE TITLE
Error installing package using yarn instead of npm

### ISSUE THREAD

**Issue by sanketdhoble** [aerospike/aerospike-client-nodejs#275]
I have package.json with  `"aerospike": "^2.7.2"` .
I am using mac.
Earlier `checks [✓] /usr/local/lib/libaerospike.a` were getting failed so 
I installed c client pkg `com.aerospike.client.c.4.1.4` on mac as well.
Now that error was gone but then following error arise.

When I run command `yarn run upgrade` it gives error on aerospike module as follows.

error /Users/sanketd/Documents/testproject/node_modules/aerospike: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/sanketd/Documents/testproject/node_modules/aerospike
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.4 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sanketd/Documents/testproject/node_modules/aerospike/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sanketd/.node-gyp/8.11.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/sanketd/.node-gyp/8.11.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/sanketd/.node-gyp/8.11.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/sanketd/Documents/testproject/node_modules/aerospike',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH e57f3d8558e9d79f83a1d12ee621e0adf8d6bb11.intermediate
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh e57f3d8558e9d79f83a1d12ee621e0adf8d6bb11.intermediate

CHECK
   [✓] /usr/local/lib/libaerospike.a
   [✓] /usr/local/include/aerospike/aerospike.h

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
  CXX(target) Release/obj.target/aerospike/src/main/client.o
  CXX(target) Release/obj.target/aerospike/src/main/config.o
  CXX(target) Release/obj.target/aerospike/src/main/events.o
../src/main/events.cc:48:13: error: unknown type name 'as_cluster_event'; did you mean 'as_cluster_s'?
                void push(as_cluster_event *event) {
                          ^~~~~~~~~~~~~~~~
                          as_cluster_s
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: 'as_cluster_s' declared here
struct as_cluster_s;
       ^
../src/main/events.cc:71:24: error: unknown type name 'as_cluster_event'; did you mean 'as_cluster_s'?
                Local<Value> convert(as_cluster_event *event) {
                                     ^~~~~~~~~~~~~~~~
                                     as_cluster_s
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: 'as_cluster_s' declared here
struct as_cluster_s;
       ^
../src/main/events.cc:43:34: error: unknown type name 'as_cluster_event'; did you mean 'as_cluster_s'?
                        cf_queue_init(&events, sizeof(as_cluster_event), 4, true);
                                                      ^~~~~~~~~~~~~~~~
                                                      as_cluster_s
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: 'as_cluster_s' declared here
struct as_cluster_s;
       ^
../src/main/events.cc:43:27: error: invalid application of 'sizeof' to an incomplete type 'as_cluster_s'
                        cf_queue_init(&events, sizeof(as_cluster_event), 4, true);
                                               ^     ~~~~~~~~~~~~~~~~~~
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: forward declaration of 'as_cluster_s'
struct as_cluster_s;
       ^
../src/main/events.cc:51:11: error: member access into incomplete type 'as_cluster_s'
                                        event->type, event->node_name, event->node_address);
                                             ^
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: forward declaration of 'as_cluster_s'
struct as_cluster_s;
       ^
../src/main/events.cc:51:24: error: member access into incomplete type 'as_cluster_s'
                                        event->type, event->node_name, event->node_address);
                                                          ^
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: forward declaration of 'as_cluster_s'
struct as_cluster_s;
       ^
../src/main/events.cc:51:42: error: member access into incomplete type 'as_cluster_s'
                                        event->type, event->node_name, event->node_address);
                                                                            ^
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: forward declaration of 'as_cluster_s'
struct as_cluster_s;
       ^
../src/main/events.cc:55:4: error: unknown type name 'as_cluster_event'; did you mean 'as_cluster_s'?
                        as_cluster_event event;
                        ^~~~~~~~~~~~~~~~
                        as_cluster_s
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: 'as_cluster_s' declared here
struct as_cluster_s;
       ^
../src/main/events.cc:55:21: error: variable has incomplete type 'as_cluster_s'
                        as_cluster_event event;
                                         ^
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: forward declaration of 'as_cluster_s'
struct as_cluster_s;
       ^
../src/main/events.cc:75:17: error: member access into incomplete type 'as_cluster_s'
                        switch (event->type) {
                                     ^
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: forward declaration of 'as_cluster_s'
struct as_cluster_s;
       ^
../src/main/events.cc:89:20: error: member access into incomplete type 'as_cluster_s'
                                        Nan::New(event->node_name).ToLocalChecked());
                                                      ^
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: forward declaration of 'as_cluster_s'
struct as_cluster_s;
       ^
../src/main/events.cc:91:20: error: member access into incomplete type 'as_cluster_s'
                                        Nan::New(event->node_address).ToLocalChecked());
                                                      ^
../aerospike-client-c/include/aerospike/aerospike.h:71:8: note: forward declaration of 'as_cluster_s'
struct as_cluster_s;
       ^
../src/main/events.cc:104:36: error: unknown type name 'as_cluster_event'
static void cluster_event_callback(as_cluster_event *event);
                                   ^
../src/main/events.cc:123:10: error: no member named 'event_callback_udata' in 'as_config_s'
        config->event_callback_udata = (void *) handle;
        ~~~~~~  ^
../src/main/events.cc:124:10: error: no member named 'event_callback' in 'as_config_s'
        config->event_callback = cluster_event_callback;
        ~~~~~~  ^
../src/main/events.cc:131:46: error: no member named 'event_callback_udata' in 'as_config_s'
        uv_handle_t *async = (uv_handle_t *)config->event_callback_udata;
                                            ~~~~~~  ^
../src/main/events.cc:146:24: error: unknown type name 'as_cluster_event'
cluster_event_callback(as_cluster_event *event)
                       ^
17 errors generated.
make: *** [Release/obj.target/aerospike/src/main/events.o] Error 1
rm e57f3d8558e9d79f83a1d12ee621e0adf8d6bb11.intermediate
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sanketd/Documents/testproject/node_modules/aerospike
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0


I am struck on this since 2 days trying to figure out what is going wrong. `npm install aerospike` works fine.

**Comment by jhecking** [comment]
The problem is that yarn sets the `PREFIX` environment variable to `/usr/local` before executing the `aerospike` module build script. The build script uses the path specified in `PREFIX` to find a copy of the C client library. If `PREFIX` is not set, it will download a suitable version of the C client as part of the build process. This is what happens when you call `npm install aerospike`, which as you said works fine.

I don't know yarn well enough to understand why it sets `PREFIX`, if there is a way to avoid this, and what other side-effects this might have.

Version 2.7.2 of the Node.js client requires version 4.1.8 of the C client library. (Never versions _might_ work but only this combination has been tested and verified.) So you _should_ be able to get yarn to work by installing [this version](https://www.aerospike.com/download/client/c/4.1.8/) of the C client first.

May I ask why you are using v2.7.2 of the Node.js client and not the latest v3.x release?

**Comment by jhecking** [comment]
Good news: I just found a work-around! You can force the Node.js client's build script to always download a copy of the C client library by setting the `DOWNLOAD` environment variable to `1`:

````
$ grep aerospike package.json
    "aerospike": "^2.7.2"
$ DOWNLOAD=1 yarn
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 32.68s.
$ node -p "require('aerospike/package').version"
2.7.2
````

**Comment by sanketdhoble** [comment]
Thanks,`DOWNLOAD=1` this works 💃 . But not able to understand everyone else in the team did not face any such issue when doing installation. yarn would work fine in other systems.

**Comment by jhecking** [comment]
You are the first person, that I heard from, who uses yarn to install the package. Just using npm seems to be much more common for our users.

I am considering renaming the `PREFIX` env var used by the installation script. But other users might depend on this var so that would be potentially a breaking change. And in any case I would only apply that fix to the v3.x version but not back-port it to v2.7.x.

**Comment by sanketdhoble** [comment]
For first time `DOWNLOAD=1`  yarn  works perfectly, but after it doing again it gives error as:
`warning: '/Users/sanketd/Documents/testproject/node_modules/aerospike/aerospike-client-c' directory exists.
warning:
warning: We will be using this directory, rather than downloading a
warning: new package. If you would like to download a new package
warning: please remove the 'aerospike-client-c' directory.`

So I had to remove the 'aerospike-client-c' directory from aerospike node_module everytime doing yarn upgrade.

**Comment by jhecking** [comment]
@sanketdhoble, I am not sure how to reproduce this? What is the exact yarn command that you run that causes this error? If I simply run `DOWNLOAD=1 yarn` multiple times, it only executes the build script of the aerospike package on the first invocation. On subsequent invocations it just returns  "success Already up-to-date."

**Comment by sanketdhoble** [comment]
`yarn run upgrade && yarn install --force` after doing this.

**Comment by jhecking** [comment]
`yarn run upgrade` just returns an error for me:

    error Command "upgrade" not found.

But if I run `yarn install --force` with DOWNLOAD set to 1 it works for me.

How are you setting the `DOWNLOAD` env variable? I believe, if you run

    $ DOWNLOAD=1 yarn run upgrade && yarn install --force

then the variable will only be set for the first command, but not when the second command executes. Try this instead:

    $ export DOWNLOAD=1
    $ yarn run upgrade && yarn install --force

**Comment by sanketdhoble** [comment]
```
export DOWNLOAD=1
yarn run upgrade && yarn install --force
```
Doing this is also not working. Only way as of know is to do `rm rf node_modules/aerospike/aerospike-client-c` and `yarn run upgrade && yarn install --force` as DOWNLOAD=1 is globally present once export is used. So not used again.

**Comment by jhecking** [comment]
Which of these two commands fails: `yarn run upgrade` or `yarn install --force`? If it's the latter, does it work if you run it without running `yarn run upgrade` first?

I am not able to reproduce this issue: `yarn install --force` with `DOWNLOAD=1` works for me, and I don't know what your upgrade script is doing.

**Comment by sanketdhoble** [comment]
@jhecking Still having the issue. Tried both separately  `DOWNLOAD=1 yarn install --force` or doing `DOWNLOAD=1 yarn run upgrade` causes the code to break, resulting in this error. 
Other members don't even need DOWNLOAD=1 command. Just doing `yarn install --force or yarn run upgrade works fine in other macs`. My mac version is v10.13.6 just for info.
 

```
SanketD-mac:projectName sanketd$ DOWNLOAD=1 yarn install --force
yarn install v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
[3/3] ⠐ aerospike
[-/3] ⠐ waiting...
error /Users/sanketd/projectName/node_modules/aerospike: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/sanketd/projectName/node_modules/aerospike
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.4 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sanketd/projectName/node_modules/aerospike/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sanketd/.node-gyp/8.11.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/sanketd/.node-gyp/8.11.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/sanketd/.node-gyp/8.11.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/sanketd/projectName/node_modules/aerospike',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH e57f3d8558e9d79f83a1d12ee621e0adf8d6bb11.intermediate
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh e57f3d8558e9d79f83a1d12ee621e0adf8d6bb11.intermediate
warning: '/Users/sanketd/projectName/node_modules/aerospike/aerospike-client-c' directory exists.
warning:
warning: We will be using this directory, rather than downloading a
warning: new package. If you would like to download a new package
warning: please remove the 'aerospike-client-c' directory.

CHECK
   [✗] /Users/sanketd/projectName/node_modules/aerospike/aerospike-client-c/package/usr/local/lib/libaerospike.a
   [✗] /Users/sanketd/projectName/node_modules/aerospike/aerospike-client-c/package/usr/local/include/aerospike/aerospike.h

make: *** [e57f3d8558e9d79f83a1d12ee621e0adf8d6bb11.intermediate] Error 1
rm e57f3d8558e9d79f83a1d12ee621e0adf8d6bb11.intermediate
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sanketd/projectName/node_modules/aerospike
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
```

**Comment by jhecking** [comment]
I'm not sure what's going on here, to be honest. The installation script is no longer looking for the Aerospike C client library in `/usr/local/lib/` like it was in your initial failed attempts. And the `node_modules/aerospike/aerospike-client-c` directory, into which the C client library is being downloaded during installation, still exists when you run `yarn install --force`. But somehow, the actual library and header files are no longer there.

You are saying that your colleagues do not have this issue. What is different between their development environment and yours? Are you using the same versions of yarn, npm, node? Are you all using Macs? Are you using the same shell? Any other differences you can think of?

**Comment by CoericK** [comment]
This is still happening, the export DOWNLOAD=1 works but seems awful to be doing this

**Comment by sanketdhoble** [comment]
@CoericK Yes the issue is still happening, but I have started to live with it. I have to do rm -rf node_modules/aerospike/aerospike-client-c to remove the c client and then DOWNLOAD=1 ...
@jhecking only difference is I guess, is my mac runs on mac OS seirra(now Mojave, issue still persists), colleagues have older version I guess.

**Comment by jhecking** [comment]
I don't want to rename the `PREFIX` variable, because it might break other users' workflows. So setting `DOWNLOAD = 1` is the recommended work-around for now. Will consider this for a future 4.0 release, whenever that might happen.
