### ISSUE TITLE
Aerospike timeouts occurring at certain connection counts

### ISSUE THREAD

**Issue by FalconerTC** [aerospike/aerospike-client-nodejs#281]
We're seeing that when a single application instance makes too many connections to the Aerospike server we start seeing massive amounts of timeouts. We found that we got timeouts at ~1.1K RPS to a single Aerospike server (resulting in ~2K batch reads) but that if we split this across two application instances we can connect fine. The only client setting we set is `maxConnsPerNode: 10000` and we should be under that limit (and the error we see is not ERR_NO_MORE_CONNECTIONS)

What determines how many request an individual client can make to an individual node? Is there other configuration limits we may be hitting here?

The stack trace is here:
```
"AerospikeError: Timeout: iterations=0 lastNode=x.x.x.x:3000
    at Function.AerospikeError.fromASError (/usr/src/app/node_modules/aerospike/lib/error.js:133:12)
    at BatchCommand.convertError (/usr/src/app/node_modules/aerospike/lib/commands/command.js:42:27)
    at BatchCommand.convertResponse (/usr/src/app/node_modules/aerospike/lib/commands/command.js:50:22)
    at asCallback (/usr/src/app/node_modules/aerospike/lib/commands/command.js:102:22)"
```
The nodejs client library is v3.0.2

**Comment by jhecking** [comment]
Are you using [`batchRead`](https://www.aerospike.com/apidocs/nodejs/Client.html#batchRead) or [`batchGet`](https://www.aerospike.com/apidocs/nodejs/Client.html#batchGet) commands? The two commands use different [batch protocols](https://www.aerospike.com/docs/guide/batch.html#batch-protocols) which are handled quite differently by the server, so it's important to know which one you are using.

Are the two application instances running on separate machines or on the same machine?

**Comment by FalconerTC** [comment]
We're using only `batchRead` currently. The separate application instances are running on the same machine, which is part of what leads me to suspect it's something wrong with the client library.

**Comment by jhecking** [comment]
`batchRead` is good because that's an asynchronous I/O operation. Did you check CPU load? Node.js is not very good at utilizing multiple processor cores, so maybe with a single Node.js instance, you were running at close to 100% CPU load on a single processor, but with two Node.js instances, you are utilizing 2 cores?

**Comment by FalconerTC** [comment]
This is being deployed on GKE. We found that we reached the ~2K read limit on a 1 core pod, which reached high CPU, and we saw the same thing on a 2 core pod where CPU stayed at lower levels. As a side note, we've also tried upgrading our Aerospike server to 4.3.0.2 and the node-client to v3.6.1 and we're seeing about the same limits.

**Comment by DomPeliniAerospike** [comment]
Issue explained and closing issue due to age.
