### ISSUE TITLE
Process is not terminated when client.close() is called 

### ISSUE THREAD

**Issue by Isikiyski** [aerospike/aerospike-client-nodejs#291]
Hello,

I didn't know how I can reopen this item https://github.com/aerospike/aerospike-client-nodejs/issues/211, so I open a new one.

I have the very same problem.

I call client.close() and simply the process hangs until I manually hit ctrl+c.

I updated to the latest aerospike version and this did not resolve the issue.
nodejs version is v8.15.0.

The odd thing is that I dump the client object AFTER i call the close() method, but all it does is simply change the `connected` property to `false`.

dump:

```Client {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  config:
   Config {
     clusterName: undefined,
     port: 3000,
     hosts: 'localhost:3000',
     policies: {},
     useAlternateAccessAddress: false,
     rackAware: undefined },
  as_client: AerospikeClient {},
  connected: false,
  captureStackTraces: false }```

**Comment by jhecking** [comment]
I don't think this is simply the same issue as #211, as the example given in that issue works as expected on the most recent client.

Do you instantiate more than one client instance in your code, e.g. by calling `Aerospike.connect()` more than once? Do you call `client.close()` with any parameters?

**Comment by Isikiyski** [comment]
I instantiate it more than once, but I just tested it with only 1 instance and calling close afterwards. Still occurring (with the latest aerospike client version).

I call client.close() without any params, however I tested it with `false` and `true` without any success

**Comment by jhecking** [comment]
Do you have a simple example with which you can reproduce the issue?

Do you connect to more than one Aerospike clusters or is there another reason why you are instantiating multiple client versions?

If you do instantiate more than one client, you may have to call `let releaseEventLoopResources = false; client.close(releaseEventLoopResources)`. If you do that, then you will have to call `Aerospike. releaseEventLoop()` once you are sure you no longer need to use Aerospike. See https://www.aerospike.com/apidocs/nodejs/module-aerospike.html#.releaseEventLoop for more info.

**Comment by Isikiyski** [comment]
After thorough testing I found that I indeed instantiate more than 1 aerospike connections.

When I have only one connection and close it afterwards the process is ended.

Thank you for your quick response
