### ISSUE TITLE
build-c-client.ps1 not found in windows?

### ISSUE THREAD

**Issue by mkgn** [aerospike/aerospike-client-nodejs#293]
I followed the docs to build the node client for windows.

Node windows build tools was installed properly. After that when executing the npm install aerospike what it says is;

Installing Aerospike C Client dependency
  ..\scripts\build-c-client.ps1 : File
  **E:\Projects\ClickNWin\src\server\src\node_modules\aerospike\scripts\build-c-client.ps1** cannot be loaded because running scripts is disabled on this system

Even though it says running scripts is disabled in the system (which is not) i don't see the build-c-client.ps1 in that path. So may be it's giving a wrong error since the file is not there.

Any idea why?

**Comment by jhecking** [comment]
I've just kicked off a Windows build on AppVeyor, which completed successfully: https://ci.appveyor.com/project/aerospike/aerospike-client-nodejs/builds/23485062. So there doesn't seem to be a problem with the build-c-client.ps1 script generally. Nothing about the Windows build process has changed in about a year or so.

What version of Windows and Visual Studio are you using? And what version of Node.js?

**Comment by jhecking** [comment]
Is this still an issue or have you been able to resolve the problem on your own?

**Comment by mkgn** [comment]
Nope, couldn't get it to work. I didn't had time to look into it further because I got few other tasks to complete. We can close the issue, i'll get back if i fail to get it done.
