### ISSUE TITLE
Support for linux-mint

### ISSUE THREAD

**Issue by mofax** [aerospike/aerospike-client-nodejs#31]
I got the following error ; am running Linux Mint

   npm install --save aerospike
-
aerospike@1.0.24 install /home/mofax/node_modules/aerospike
node-gyp rebuild

make: Entering directory `/home/mofax/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
error: linuxmint17 is not supported.
make: *** [aerospike-client-c/lib/libaerospike.a] Error 1
make: Leaving directory `/home/mofax/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mofax/node_modules/aerospike
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! aerospike@1.0.24 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@1.0.24 install script.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--save" "aerospike"
npm ERR! cwd /home/mofax
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by ryanwitt** [comment]
```
error: linuxmint17 is not supported.
```

Maybe rename to "Support building on Linux Mint"?

**Comment by GayathriKaliyamoorthy** [comment]
fix is available from release [1.0.49](https://github.com/aerospike/aerospike-client-nodejs/releases/tag/1.0.49).
