### ISSUE TITLE
Error while installing in Windows

### ISSUE THREAD

**Issue by santhalakshmiv** [aerospike/aerospike-client-nodejs#318]
Facing the following error when trying to install in Windows.

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209
,5): error MSB6006: "cmd.exe" exited with code 1. [C:\aerospike-vm\aerospikedemo\node_modules\aerospike\build\aerospike
-client-c.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\aerospike-vm\aerospikedemo\node_modules\aerospike
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN aerospikedemo@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aerospike@3.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aerospike@3.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by jhecking** [comment]
I’ll need more info than this. Esp. since the [Windows CI builds in AppVeyor](https://ci.appveyor.com/project/aerospike/aerospike-client-nodejs) don’t show any issues.

Can you provide the full log that should have been listed after this line:

> npm ERR! A complete log of this run can be found in:

If it’s too large to post here, maybe you can post it as a Gist on GitHub or on pastebin.com?

**Comment by santhalakshmiv** [comment]
Created a Gist on Github. Here is the link, <script src="https://gist.github.com/santhalakshmiv/9454804d625e84f6c0fcb4f87ef4457a.js"></script>

Thank you for the help.

**Comment by Iezious** [comment]
the same problem on several machines with same result:

  ..
  D:\Temp\ttt\node_modules\aerospike\scripts\build-c-client.ps1 : Failed to build aerospike-client-c dependency
  At line:1 char:1
  + ..\scripts\build-c-client.ps1 -Configuration Release -NodeLibFile C:\ ...
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
      + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build-c-client.ps1

  Failed to build aerospike-client-c dependency
  At D:\Temp\ttt\node_modules\aerospike\scripts\build-c-client.ps1:140 char:2
  +     throw "Failed to build aerospike-client-c dependency"
  +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : OperationStopped: (Failed to build...nt-c dependency:String) [], RuntimeException
      + FullyQualifiedErrorId : Failed to build aerospike-client-c dependency

**Comment by jhecking** [comment]
Thanks, @Iezious 

For either of you: Is this the first time that you are trying to install the client on a Windows machine?  Or have you been able to install the client successfully before, and are only now running into this problem?

What would be really helpful, is if you could check if you can find a `*. msbuild.log` log file somewhere under the aerospike-client-nodejs module directory, after the unsuccessful build.

**Comment by Iezious** [comment]
Unfortunately scrip cleanups all the temp and build files on fail, so no. I have npm log but it doesn't contain any error.

[2019-10-31T13_57_01_541Z-debug.log](https://github.com/aerospike/aerospike-client-nodejs/files/3794333/2019-10-31T13_57_01_541Z-debug.log)

**Comment by jhecking** [comment]
> Nuget packages for .net core installed and works on some of them.

You mean the build works on some machines but not others?

Unfortunately, the npm logs don’t really help me. And I don’t have a Windows machine available at the moment to try to reproduce this. So I’m afraid we are stuck unless we can find out where exactly in the build process the error occurs.

**Comment by Iezious** [comment]
No, I meant I have several developers trying - some of them both node and c# devs, some pure node. ALL have the same problem installing aerospike npm on win machines, but all c# devs have working nuget.

**Comment by jhecking** [comment]
I don’t think it’s the ps1 script that removes the logs. Can you try cloning the aerospike-client-nodejs repo on one of your machines and then running `npm install` inside that package directly? I think that should leave the msbuild.log file in place.

**Comment by santhalakshmiv** [comment]
Same here. Several developers trying in their Win machine and facing the same issue as below.
First time installation for all of us.

I don't see *.msbuild.log file. Where can I see the log?

 Installing Aerospike C Client dependency
  ..\scripts\build-c-client.ps1 : File
  C:\Users\Santha\AppData\Roaming\npm\node_modules\aerospike\scripts\build-c-client.ps1 cannot be loaded because runnin
  g
  scripts is disabled on this system. For more information, see about_Execution_Policies at
  https:/go.microsoft.com/fwlink/?LinkID=135170.
  At line:1 char:1
  + ..\scripts\build-c-client.ps1 -Configuration Release -NodeLibFile C:\ ...
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : SecurityError: (:) [], PSSecurityException
      + FullyQualifiedErrorId : UnauthorizedAccess
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209
,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Santha\AppData\Roaming\npm\node_modules\aerospike\build\aer
ospike-client-c.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Santha\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Santha\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Santha\AppData\Roaming\npm\node_modules\aerospike
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aerospike@3.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aerospike@3.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Santha\AppData\Roaming\npm-cache\_logs\2019-10-31T17_49_33_671Z-debug.log

**Comment by Iezious** [comment]
```  + CategoryInfo          : SecurityError: (:) [], PSSecurityException
  + FullyQualifiedErrorId : UnauthorizedAccess
```

Set-ExecutionPolicy Unrestricted Process 
will fix this problem, but then you will find the problem I faced.

**Comment by santhalakshmiv** [comment]
@Iezious Thank you. After running the command, I am able to install without any issue.

**Comment by Iezious** [comment]
ok, fixed

1. windows-build-tools must be vs2015 not latest, so maybe install notes must be changed to

`npm i windows-build-tools -g --vs2015`

2. not sure - does p1 contain win8.1 sdk inside, I installed it before vs2015 build tools, if not - it also is to be mentioned in install notes.

**Comment by jhecking** [comment]
Thanks for both your feedback and help, @lezious & @santhalakshmiv!

I've updated the Windows Readme here: https://github.com/aerospike/aerospike-client-nodejs/blob/windows-readme/README_WINDOWS.md. Please take a look and let me know if this covers everything now, based on your recent experience.
