### ISSUE TITLE
Wrong persistence of Boolean attributes.

### ISSUE THREAD

**Issue by pablonazareno** [aerospike/aerospike-client-nodejs#32]
I'm having some issue when saving an object with Boolean attributes.
 Its apparently is converting them to objects.

This code in NodeJs
```javascript
var aerospike = require('aerospike');
var client = aerospike.client(connectionSetting);
client.connect(function(response) {
	if (response.code === aerospike.status.AEROSPIKE_OK) {
		var digest = aerospike.key('test', 'test', 'title');
		var value = {
			header: {
				banners: [],
				apply_banner: false
			}
		};
		client.put(digest, value, console.log);
	} else {
		console.error('SOMETHING IS WRONG');
	}
});
```
Generate this object at Aerospike DB.
```
ascli get test test title
{"header": { "banners": [ ], "apply_banner": { } }}
```

Server version 3.4.0
NodeJs module version 1.0.25
 
Thanks
Pablo

**Comment by mhiguera** [comment]
Unfortunately, booleans are not currently supported. Please check this:
www.aerospike.com/docs/guide/data-types.html

You may use an integer instead, or a (de)serializer if you don't mind the
overhead. Personally, I've found MessagePack to be fast enough while savvy,
it worths a try!

**Comment by GayathriKaliyamoorthy** [comment]
In the latest release, if one tries to write a bin with a boolean value, the write is failed with the error message. "Boolean datatype is not supported".
