### ISSUE TITLE
Wont install on Windows7

### ISSUE THREAD

**Issue by ankurjasoria** [aerospike/aerospike-client-nodejs#33]
When using below link for NodeJS with windows7 and run this command "$ npm install aerospike"
http://www.aerospike.com/docs/client/nodejs/install/

Error Message :
C:\nodecellar> npm install aerospike
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: aerospike@1.0.26
npm ERR! notsup Valid OS:    linux,darwin
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\
\npm-cli.js" "install" "aerospike"
npm ERR! cwd C:\nodecellar
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code EBADPLATFORM
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\nodecellar\npm-debug.log
npm ERR! not ok code 0
C:\nodecellar>

**Comment by GayathriKaliyamoorthy** [comment]
Hi
Currently, Aerospike node.js client is not supported on windows 7.
For the list of supported OS's refer the README here.
https://github.com/aerospike/aerospike-client-nodejs/blob/master/README.md

Aerospike C# API and Aerospike libevent is compatible with windows platform.

Thanks

**Comment by ankurjasoria** [comment]
@GayathriKaliyamoorthy : Thnxx for your quick reply.
I am using NodeJS on Windows7 machine and want to connect Aerospike DB so How could I perform this?

**Comment by GayathriKaliyamoorthy** [comment]
Sorry we do not support windows platform currently. Will notify when support windows7.

Thanks

**Comment by ankurjasoria** [comment]
If I'll connect Linux Machine from Window7 then Could I perform my Work?

**Comment by GayathriKaliyamoorthy** [comment]
If you are running your application in a linux machine, then this will work.

**Comment by wchu-citrusleaf** [comment]
Will leave this open for future feature enhancement, even though currently there is no timeline.

**Comment by ualtinok** [comment]
Is there any news on this? We were planning to use Aerospike on our next project but we'll fallback to Redis again because of this issue. Hope you have a timeline now. Thanks

**Comment by tracker1** [comment]
@ankurjasoria @ualtinok if you know you will be running on Windows, you can use [edge.js](https://www.npmjs.com/package/edge) as a shim to the .Net client.  Which may be your best bet as an interim solution... I've used it (edge.js) before, and its' pretty straight forward.

I too wish that the aerospike client for node used a JS interface, instead of the C interface, which would be less problematic, and easier to support across platforms (at a potentially modest performance cost).

**Comment by ualtinok** [comment]
@tracker1 Nice workaround. We'll only use Windows for development so I will check on that if it's a viable option. Thanks

**Comment by nullivex** [comment]
I would like to use Aerospike too.

We use Debian / Gentoo / Ubuntu servers however a few of our developers work on Windows.

I dont mind not being able to run the server on windows. But this package not supporting Windows is a huge drawback.

I am willing to try my own hand at supporting this would anyone be willing to give me any direction on what might need to be done to accomplish this?

**Comment by xantin** [comment]
@nullivex so try to use vagrant and install aerospike-client-nodejs there and also develop there.

**Comment by jhecking** [comment]
Closing this old issue.

Another option to using Vagrant on Windows is to use the (relatively new) [Windows Subsystem for Linux (WSL)](https://msdn.microsoft.com/commandline/wsl/about) (a.k.a. "Bash on Ubuntu on Windows"). While Aerospike does not officially support this, informal testing so far has shown that this solution works quite well.

**Comment by evalsocket** [comment]
I think docker /vagrant can solve your problem. 
Install aerospike virtually
