### ISSUE TITLE
There is no "legal" way to pass int64 as a key.

### ISSUE THREAD

**Issue by SergeyFromHell** [aerospike/aerospike-client-nodejs#347]
Currently, aerospike Key class only accepts ints(typeof == 'number'), strings and buffers.
But AS supports bit integers natively. So I propose to extend client to accept some type of 64-bit integers as a keys (and in ops too).
Right now I use some hack to create 64-bit keys:
```
         let isDigest = (key instanceof Uint8Array) && (key.length == 20);
         if (typeof (key) == 'bigint') {
            const hash = crypto.createHash('ripemd160');
            hash.update(set);
            const b = Buffer.alloc(9);
            b[0] = 1;
            b.writeBigInt64BE(key, 1);
            hash.update(b);
            key = hash.digest();
            isDigest = true;
        }
        return new aerospike.Key(this._namespace, set, isDigest ? null : key, isDigest ? key : null);
```
It is ported from official C client code.
Maybe add something like this? BigInts has been included to JS standarts for long time.

**Comment by jhecking** [comment]
Agree. Makes sense to allow BigInt as a record key.
