### ISSUE TITLE
Document how to set TLS name for seed hosts

### ISSUE THREAD

**Issue by RatnadeepSimhadri** [aerospike/aerospike-client-nodejs#377]
Hi Team, 

Is it possible to specify a specific TLS name as part of the Hosts Object. I did not find any documentation on it
I could see that both Java and Python Clients Have an option to include **tlsname**  as part of the Hosts Object

Python 

<img width="804" alt="Screen Shot 2020-08-06 at 9 02 55 PM" src="https://user-images.githubusercontent.com/9788837/89607825-4a982d80-d828-11ea-8393-86cd6f8f7a81.png">

Java
<img width="1312" alt="Screen Shot 2020-08-06 at 9 05 12 PM" src="https://user-images.githubusercontent.com/9788837/89607932-8fbc5f80-d828-11ea-9b12-044a7196945f.png">

**Comment by jhecking** [comment]
Yes, it's possible, but unfortunately it's indeed not documented at all! The only way to specify the TSL name right now is to specify the seed hosts as a single comma-separated string, using the following format:

    hostname1[:tlsname1][:port1],...

E.g. `192.168.33.10:tlsname1:3000,192.168.33.11:tlsname2:3000`.

**Comment by RatnadeepSimhadri** [comment]
Sure thanks. Thats Good to know

**Comment by RatnadeepSimhadri** [comment]
It Would be a Nice to have it as part of the Host {} as well

**Comment by jhecking** [comment]
> It would be a nice to have it as part of the Host {} as well.

I added support for setting tlsname via `Host` object in #382. Will include this as part of the next release (v3.17.0).

**Comment by RatnadeepSimhadri** [comment]
Thank you @jhecking
