### ISSUE TITLE
Failed to build aerospike-client-c dependency

### ISSUE THREAD

**Issue by georgeglessner** [aerospike/aerospike-client-nodejs#379]
I am running into an error on my new computer when trying to run `npm i` on a project of mine that utilizes aerospike. I have installed pre-reqs for windows and set execution policy. 

Versions:
OS: Windows 10 64bit
Node: 12.18.3
Aerospike: 3.16.1
NPM: 6.14.17

Output of error log: https://pastebin.com/6JLLjtsS

**Comment by georgeglessner** [comment]
The issue is because my username has a space in it

**Comment by jhecking** [comment]
> The issue is because my username has a space in it

I can't really tell that from the npm logs you provided. The installation fails while executing the install script, i.e. presumably during this step:

```
              'action': [
                'powershell', 'scripts/build-c-client.ps1',
                    '-Configuration', "$(ConfigurationName)",
                    '-NodeLibFile', "<(node_root_dir)/<(target_arch)/node.lib"
              ]
```

But it's not clear to me why or how that script fails. Do you have any further insights? E.g. maybe you can try to run that script manually and see if there is any more specific error message?

In the logs, you user directory is repeatedly listed as `C:\Users\George \` - is that really just `George` followed by a single space, or is the directory name really something like `George Glessner` and somehow the 2nd part got truncated somewhere? If so, that seems to happen even before the installation script is called.

**Comment by georgeglessner** [comment]
@jhecking yes I believe the issue is from `node_root_dir` and I think it is actually a node-gyp issue after doing more research. I found a node-gyp PR that supposedly fixed the space in root directory issue but mine still fails. 

You are also correct my directory is `George Glessner`, I was trying to exclude my full name but forgot my username here is my full name 😆 

This is my work computer I am trying to install on, I installed on the "admin" account on the computer and it worked just fine. I am going to work with my hardware team tomorrow to get my account set back up on the domain (how my old computer was setup with the working aerospike install) which will make my username contain no spaces. I can report back after that change is made.

**Comment by jhecking** [comment]
Thanks for the follow-up. I'll close this issue for now, since it seems there is nothing we can do to fix this issue in the client installation scripts. But feel free to reopen the issue if there's something I missed and that needs to be addressed.
