### ISSUE TITLE
batch_get() vs batchGet()

### ISSUE THREAD

**Issue by ryanwitt** [aerospike/aerospike-client-nodejs#38]
The [docs on the website](http://www.aerospike.com/docs/client/nodejs/usage/kvs/read.html) suggest that the function for reading multiple keys at once is called `batch_get()`, but this leads to an error on the latest driver:

```
TypeError: Object #<AerospikeClient> has no method 'batch_get'
```

**Comment by GayathriKaliyamoorthy** [comment]
It's a typo error in Doc, I'll fix it in the next release.
The correct API invocation is `batchGet`

Thanks
