### ISSUE TITLE
Cannot find module '../build/Release/aerospike.node'

### ISSUE THREAD

**Issue by niloy** [aerospike/aerospike-client-nodejs#39]
I installed "aerospike" via npm on Ubuntu 14.04. I created a js file like below:

```js
var aerospike = require("aerospike");
```

When I run the file, I get this error:

> Cannot find module '../build/Release/aerospike.node'

**Comment by niloy** [comment]
Sorry, my mistake.

**Comment by ScionOfBytes** [comment]
@niloy What was your mistake?

**Comment by afficiona** [comment]
@niloy Yes, even am facing such an issue. What was your mistake?

**Comment by jellyedwards** [comment]
For me, I was using the latest version and downgrading worked. Specifically, I downgraded to 2.4.4 but I didn't try higher versions.

**Comment by jhecking** [comment]
@jellyedwards, what Node.js version and OS are you using? I suspect that depending on the Node.js and/or node-gyp version or configuration the `aerospike.node` addon file might end up in a different location. I'm considering using the `node-bindings` module to resolve this issue for the next release. But I would like to confirm first if this is actually the cause of the problem.

**Comment by jellyedwards** [comment]
@jhecking OS is Ubunto 16.10 and node version is v4.2.6 - hope this helps
