### ISSUE TITLE
Aerospike Expressions

### ISSUE THREAD

**Issue by tacyarg** [aerospike/aerospike-client-nodejs#406]
The client library is missing documentation and support for the newer Expressions api.

https://www.aerospike.com/docs/guide/expressions/

**Comment by unbalanced** [comment]
+1 
is it on the agenda to add it?

**Comment by jhecking** [comment]
Its work in progress: https://github.com/aerospike/aerospike-client-nodejs/tree/expressions. Do take a look if you feel adventurous. Not all expressions are supported yet, and it's still lacking documentation, but the existing [tests](https://github.com/aerospike/aerospike-client-nodejs/blob/expressions/test/exp.js) show how the API can be used.

**Comment by unbalanced** [comment]
Truly appreciating the feedback. Thanks @jhecking

**Comment by rbotzer** [comment]
Expression supports was added in [release 4.0.1](https://download.aerospike.com/download/client/nodejs/notes.html#4.0.1).
