### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by jainlibra** [aerospike/aerospike-client-nodejs#429]
I am using nodejs client 3.16.6. When I run a test using jest,I always hit the segmentation fault issue while doing a put. The console log after setSerialized invocation is not printed.
I was getting this issue in Mac(Xcode missing),so tried using a docker container with CentOS.Hit the issue there as well

env details:
uname -a
Linux a2e7fb134efa 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
node version 14.15.4
"jest": "26.6.3",
"jest-junit": "10.0.0"

package.json:
"scripts": {
    "build": "tsc -p tsconfig.json",
    "build:watch": "tsc-watch -p tsconfig.json",
    "clean": "rimraf lib reports && (jest --clearCache || true)",
    "format": "prettier --config ../.prettierrc --write \"./**/*.{ts,js,json,md}\" --ignore-path .gitignore",
    "guest:client": "node lib/src/guest.client.js",
    "prebuild": "npm run clean",
    "purge": "npm run clean && rimraf node_modules",
    "lint": "eslint -c ./.eslintrc.js --resolve-plugins-relative-to . --parser-options=project:tsconfig.json --max-warnings 0 'src/**/*.ts' 'tests/**/*.ts'",
    "lint:fix": "eslint -c ./.eslintrc.js --fix --resolve-plugins-relative-to . --parser-options=project:tsconfig.json --max-warnings 0 'src/**/*.ts' 'tests/**/*.ts'",
    "test": "jest --config jest.config.js --coverage --runInBand --forceExit",
    "test:watch": "jest --config jest.config.js --watch"
  },
  "dependencies": {
    "@nestjs/common": "7.6.5",
    "@nestjs/core": "7.6.5",
    "aerospike": "^3.16.6",
    "chalk": "4.1.0",
    "got": "11.8.1",
    "joi": "14.3.1",
    "js-yaml": "3.14.1",
    "logform": "2.2.0",
    "nest-schedule": "0.6.4",
    "redlock": "4.2.0",
    "reflect-metadata": "0.1.13",
    "request": "2.88.2",
    "request-promise": "4.2.6",
    "rxjs": "6.6.3",
    "winston": "3.3.3"
  },
  "devDependencies": {
    "@types/express": "4.17.7",
    "@types/jest": "25.2.3",
    "@types/redis": "2.8.28",
    "@types/redlock": "4.0.1",
    "@types/js-yaml": "3.12.6",
    "@types/joi": "14.3.4",
    "@types/request-promise": "4.1.47",
    "@types/supertest": "2.0.10",
    "@types/tmp": "0.2.0",
    "@typescript-eslint/eslint-plugin": "2.34.0",
    "@typescript-eslint/eslint-plugin-tslint": "2.34.0",
    "@typescript-eslint/parser": "2.34.0",
    "create-test-server": "3.0.1",
    "eslint": "7.18.0",
    "eslint-config-prettier": "6.15.0",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "eslint-plugin-prettier": "3.3.1",
    "jest": "26.6.3",
    "jest-junit": "10.0.0",
    "prettier": "2.2.1",
    "redis": "^3.0.2",
    "rimraf": "3.0.2",
    "supertest": "4.0.2",
    "ts-jest": "25.5.1",
    "ts-mockito": "2.6.1",
    "ts-node": "8.10.2",
    "tsc-watch": "4.2.9",
    "tsconfig-paths": "3.9.0",
    "tslint": "6.1.3",
    "typescript": "3.9.2"
  }

The test snippet

describe('aerospike store', () => {
        console.log('aerospike test start');
        it('sets and gets', async () => {
            console.log("here in aerospike test");
            const stateStore: AerospikeKeyValueStore<string> = new AerospikeKeyValueStore({
                expire: 0,
                namespaces: ['development', 'test-key'],
                hosts: ['platform115.dev.ind.in'],
                retryInOtherDCs: false,
                user: 'raventest',
                password: 'raventest',
                dbnamespace: 'raventest',
                set: 'testAeroHAA',
                environment: 'development'
            });
            console.log("before asserting");
            await stateStore.setSerialized('my-key', 'test');
            console.log("after setting");
            await stateStore.getSerialized('my-key');
            //console.log(result);
            //await expectSetsAndGets(stateStore);
        });

export class AerospikeKeyValueStore<T> extends JSONKeyValueStore<T> {
    private readonly logger = createLogger(createLoggerOptions(AerospikeKeyValueStore.name));
    private readonly namespacePrefix: string;
    // private readonly cluster: ClusterConfig;
    // private readonly retryInOtherDCs: boolean;
    private readonly expire: number | undefined;
    private readonly client: any; // eslint-disable-line
    private readonly dbnamespace: string;
    private readonly dbset: string;

    constructor(config: Config) {
        super();

        const defaultPolicy = {
            totalTimeout: 10000,
            maxRetries: 4,
            socketTimeout: 10000
        };
        const hostsArr = [];
        for (const host of config.hosts) {
            hostsArr.push({ addr: host, port: 3000 });
        }
        this.namespacePrefix = [...config.namespaces, ''].join(':');
        // this.cluster = config.clusters;
        // this.retryInOtherDCs = config.retryInOtherDCs;
        this.expire = config.expire;
        this.client = Aerospike.client({
            hosts: hostsArr,
            // port: 3000, // default aerospike port
            user: config.user,
            password: config.password,
            policies: {
                apply: defaultPolicy,
                batch: defaultPolicy,
                info: defaultPolicy,
                operate: defaultPolicy,
                query: defaultPolicy,
                read: defaultPolicy,
                remove: defaultPolicy,
                scan: defaultPolicy,
                write: defaultPolicy
            }
        });
        this.dbnamespace = config.dbnamespace;
        this.dbset = config.set;
    }

    public async delete(key: string): Promise<void> {
        const cacheKey = new Aerospike.Key(this.dbnamespace, this.dbset, this.buildNamespacedKey(key));
        try {
            if (!this.client.isConnected()) {
                await this.client.connect();
            }
            await this.client.remove(cacheKey);
        } catch (error) {
            this.logger.error('error occured while deleting key', error);
        } finally {
            await this.client.close();
        }
        this.logger.debug('Removed record:', key);
    }
    public keys(pattern: string): Promise<string[]> {
        throw new Error('Method not implemented.');
    }
    public async getSerialized(key: string): Promise<string | undefined> {
        const cacheKey = new Aerospike.Key(this.dbnamespace, this.dbset, this.buildNamespacedKey(key));
        let valueRetrieved;
        try {
            if (!this.client.isConnected()) {
                await this.client.connect();
            }
            valueRetrieved = await this.client.get(cacheKey);
        } catch (error) {
            this.logger.error('error occured while getting value corresponding to key', error);
        } finally {
            await this.client.close();
        }
        return valueRetrieved.bins.value;
    }
    public async setSerialized(key: string, serializedValue: string): Promise<void> {
        const cacheKey = new Aerospike.Key(this.dbnamespace, this.dbset, this.buildNamespacedKey(key));
        try {
            if (!this.client.isConnected()) {
                await this.client.connect();
            }
            // setting a write policy with the key will allow the key to be returned in get and store it in aerospike
            // however,facing a timeout issue when using it.
            // let policy = new Aerospike.policy.WritePolicy({
            // exists: Aerospike.policy.exists.CREATE,
            // key: Aerospike.policy.key.SEND
            // });
            await this.client.put(
                cacheKey,
                { value: serializedValue },
                { ttl: this.expire }
                // { exists: Aerospike.policy.exists.CREATE_OR_REPLACE }
            );
        } catch (error) {
            this.logger.error('error occured while adding/updating state for key', error);
        } finally {
            await this.client.close();
        }
    }

    private buildNamespacedKey(keyName: string): string {
        return [this.namespacePrefix, keyName].join('');
    }
}

**Comment by jainlibra** [comment]
I was also running into Fatal error: glibc detected an invalid stdio handle but doing npm install aerospike again got rid of this issue

**Comment by jhecking** [comment]
Hi @jainlibra,

I'm able to reproduce a segfault using this slightly simplified test code:

```
import * as Aerospike from 'aerospike'

class AerospikeKeyValueStore {
  private logger = console
  private namespacePrefix: string;
  private expire: number | undefined;
  private client: any; // eslint-disable-line
  private dbnamespace: string;
  private dbset: string;

  constructor(config: any) {
    const defaultPolicy = {
      totalTimeout: 10000,
      maxRetries: 4,
      socketTimeout: 10000
    };
    //const hostsArr = [];
    //for (const host of config.hosts) {
    //  hostsArr.push({ addr: host, port: 3000 });
    //}
    this.namespacePrefix = [...config.namespaces, ''].join(':');
    this.expire = config.expire;
    this.client = Aerospike.client({
      // hosts: hostsArr,
      // user: config.user,
      // password: config.password,
      policies: {
        apply: defaultPolicy,
        batch: defaultPolicy,
        info: defaultPolicy,
        operate: defaultPolicy,
        query: defaultPolicy,
        read: defaultPolicy,
        remove: defaultPolicy,
        scan: defaultPolicy,
        write: defaultPolicy
      },
      log: {
        level: Aerospike.log.DEBUG,
        file: process.stdout.fd
      }
    });
    this.dbnamespace = config.dbnamespace;
    this.dbset = config.set;
  }

  public async getSerialized(key: string): Promise<string | undefined> {
    const cacheKey = new Aerospike.Key(this.dbnamespace, this.dbset, this.buildNamespacedKey(key));
    let valueRetrieved;
    try {
      if (!this.client.isConnected()) {
        await this.client.connect();
      }
      valueRetrieved = await this.client.get(cacheKey);
    } catch (error) {
      this.logger.error('error occured while getting value corresponding to key', error);
    } finally {
      await this.client.close();
    }
    return valueRetrieved.bins.value;
  }

  public async setSerialized(key: string, serializedValue: string): Promise<void> {
    const cacheKey = new Aerospike.Key(this.dbnamespace, this.dbset, this.buildNamespacedKey(key));
    try {
      if (!this.client.isConnected()) {
        await this.client.connect();
      }
      await this.client.put(
        cacheKey,
        { value: serializedValue },
        { ttl: this.expire }
      );
    } catch (error) {
      this.logger.error('error occured while adding/updating state for key', error);
    } finally {
      await this.client.close();
    }
  }

  private buildNamespacedKey(keyName: string): string {
    return [this.namespacePrefix, keyName].join('');
  }
}

async function main () {
    const stateStore: AerospikeKeyValueStore = new AerospikeKeyValueStore({
      expire: 0,
      namespaces: ['development', 'test-key'],
      // hosts: ['...'],
      // user: '...',
      // password: '...',
      dbnamespace: 'test',
      set: 'testAeroHAA'
    });
    console.log("before asserting");
    await stateStore.setSerialized('my-key', 'test');
    console.log("after setting");
    await stateStore.getSerialized('my-key');
}

main()
```

This is what I get when I run this code:

```
> tsc index.ts && node index.js
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [config.cc:241] [config_from_jsobject] - Parsing global policies: success
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [config.cc:329] [config_from_jsobject] - Built as_config instance from JS config object
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [client.cc:80] [New] - Aerospike client initialized successfully
before asserting
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [events.cc:57] [push] - Cluster event 0 triggered by node "BB9030011AC4202" ([::1]:55011)
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [events.cc:57] [push] - Cluster event 0 triggered by node "BB9040011AC4202" (192.168.1.15:55014)
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [client.cc:99] [Connect] - Successfully connected to cluster: Enjoy your cake!
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [command.cc:66] [Callback] - Executing JS callback for Connect command
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [put_async.cc:73] [PutAsync] - Sending async put command
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [command.cc:66] [Callback] - Executing JS callback for Put command
Jul 28 2021 01:43:35 UTC: DEBUG(42390) [client.cc:114] [Close] - Closing the connection to aerospike cluster
after setting
node: warning: node crashed, killed by SIGSEGV.
node itself has not crashed, but for transparency,
it will now kill itself (without dumping core) with the same signal


warnings can be silenced by the --no-warnings (-n) option
Segmentation fault: 11
```

The reason this is happening is that you are repeatedly calling `client.connect()` and `client.close()` on the same client object. That is not a supported usage pattern. Should that cause a segfault? Definitely not, and I will address that. But probably just by instead raising an Error when `client.connect()` is called after `client.close()`.

Is there a specific reason you cannot keep the connection to the Aerospike cluster alive? Establishing a new connection is a fairly expensive operation for the client, esp. on large clusters, as it needs to connect to every single server node to fetch the partition map, etc. If you really do need to establish a new client connection, then you need to do so by creating a new Aerospike.Client instance. Note, however, that in that case you need to call `client.close(false)`, i.e. with the `releaseEventLoop` parameter set to `false`. And when you want to shut down the program, you'll have to call `Aerospike.releaseEventLoop()` to allow the Node.js event loop to shut down. Please refer to the documentation for more details: https://docs.aerospike.com/apidocs/nodejs/module-aerospike.html#.releaseEventLoop

**Comment by jainlibra** [comment]
Thanks @jhecking. That resolved the issue.
