### ISSUE TITLE
Confusing Behavior of client.info('statistics') on Cluster

### ISSUE THREAD

**Issue by woozyking** [aerospike/aerospike-client-nodejs#43]
This might be caused by my lack of understanding of JS/Node.js in general but when I tried to do something like this (assuming client being successfully connected already):

```
var i = 0;

client.info('statistics', function(err, response, host) {
  console.log(err, i++);
});
```

The output would be:

```
{ code: 0, message: null, func: null, file: null, line: null } 0
{ code: 0, message: null, func: null, file: null, line: null } 1
{ code: 0, message: null, func: null, file: null, line: null } 2
{ code: 0, message: null, func: null, file: null, line: null } 3
{ code: 0, message: null, func: null, file: null, line: null } 4
{ code: 0, message: null, func: null, file: null, line: null } 5
{ code: 0, message: null, func: null, file: null, line: null } 6
{ code: 0, message: null, func: null, file: null, line: null } 7
```

Which indicates to me that this anonymous callback function gets invoked N times, where N being the number of nodes of given cluster in the client connection.

I know there might be techniques to work around this behavior to have a streamlined workflow to collect all statistics of all the nodes within given cluster synchronously (?), but wouldn't it be easier to have this request (I haven't tested other requests through `client.info` API) behave somewhat similar to `client.batchGet` where the callback would get an array of `results` and the callback being effectively just executed once?

I'm happy to elaborate more on this issue. My specific use case is to have a client regularly checks a given Aerospike cluster's health, and maybe there's a better and easier way to do it? Regardless, in my opinion the current behavior of `client.info('statistics')` is a little bit weird and due to the async nature of js/node.js, it's really hard to collect info from a cluster of nodes.

To give an example of this undesirable behavior, I'm using `async`, and `client.info('statistics')` is one of the tasks (I'm using `async.parallel` if this is relevant):

```
var jobs = [];

// some other jobs

jobs.push(function(callback) {
  client.info('statistics', function(err, response, host) {
    callback(err);
  });
});
```

And `async` would complain to me as `Error: Callback was already called.` (expected as my observation in the first example).

**Comment by GayathriKaliyamoorthy** [comment]
Hi @woozyking 

Are you still facing the issue, I tried to reproduce this and could not. Please do share the code snippet if you are facing this issue.

Thanks

**Comment by woozyking** [comment]
@GayathriKaliyamoorthy I think the code snippet would still be the same I posted above. If it can no longer be reproduced by you using `async` library, then this should be good to be closed.

I no longer do this check though on our Aerospike cluster, but just a simple connectivity test.

To me `client.info('statistics')` seemed more appropriate to be `client.on('statistics', function(...) {...})` with the original behavior I posted this issue about, at least less confusing. I'm not entirely sure about the new behavior now, but I appreciate your help.

**Comment by ameykpatil** [comment]
I recently faced the same issue (with node.js client version 2.2.0)
I wanted a count of records in a set, so I was calling
`client.info('sets/test/testset', callback)` (& then parsing to get `n_objects`)
I was getting `callback already called` error when using the multi-node cluster but was working fine on a single node cluster.

**Comment by jhecking** [comment]
The info method works as designed, i.e. it returns the requested info per each cluster node through the callback method as soon it is received by the client. Note that the method also has an additional, 2nd callback, which is called once all the nodes have responded:

    Client.prototype.info = function (request, host, policy, infoCb, doneCb) { ... }

See the [API docs](http://www.aerospike.com/apidocs/nodejs/Client.html#info) for the full method signature.

But I get how this behavior be a bit unexpected and that for many use cases it would be more convenient to have all the info returned in a single callback. I'll consider this a feature request for a future update. A pull request would be welcome as well. :-)

**Comment by jhecking** [comment]
I've added a new `Client#infoAll` method, which queries all the cluster nodes and returns the results in a single callback method call. This will be included in the next release, which is tentatively scheduled for next week.
