### ISSUE TITLE
npm install aerospike does not work with Apple M1 chip

### ISSUE THREAD

**Issue by dheerajtiwari** [aerospike/aerospike-client-nodejs#430]
npm ERR! notsup Unsupported platform for aerospike@3.16.6: wanted {"os":"linux,darwin,win32","arch":"x64"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    linux,darwin,win32
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64

**Comment by jhecking** [comment]
Thanks for reporting the issue. Unfortunately, I don't have a new M1-based mac yet to replicate this. :-)

In order for the Node.js client to support the arm64 platform, we'll first need a build of the Aerospike C client SDK for that platform, since the Node.js client is just a wrapper around the C client. I'll have to check with the Aerospike team what's the plan for that.

**Comment by jhecking** [comment]
At the moment there are no concrete plans yet to support the Aerospike C client on arm64.

**Comment by eagleeye** [comment]
as a workaround you can install `aerospike-client-nodejs` inside of Docker, and run it from there. Just don't forget to specify platform: amd64 when you start it. Example of my `docker-compose.yaml` file
```
version: '2.4'
services:
  eventproclambda:
    build: .
    platform: linux/amd64
```
and Dockerfile stays normal
```
FROM node:14.18.2

WORKDIR /usr/src/app

COPY package*.json ./

RUN ["npm", "--verbose" ,  "ci"]

COPY . .
ENTRYPOINT [ "npm", "test" ]
```

**Comment by jhecking** [comment]
Quick update: There has been some progress on getting the Aerospike C client to work on Apple Silicon - ref. https://github.com/aerospike/aerospike-client-c/pull/120.

**Comment by rbotzer** [comment]
For the server, and in general running amd64 containers on M1 processors see [aerospike-community/docker-amd64-mac-m1](https://github.com/aerospike-community/docker-amd64-mac-m1).

Otherwise, native ARM support will come to the C, Node.js and Python clients later this year.

**Comment by DomPeliniAerospike** [comment]
Native arm support was added in Client version 5.2.0.  Apple M1 chips should work now. Closing issue now.
