### ISSUE TITLE
[BUG] Invalid C client archive for Ubuntu 16

### ISSUE THREAD

**Issue by unreadable** [aerospike/aerospike-client-nodejs#432]
OS: System Linux 4.4.0-87-generic (Ubuntu 16)
Aerospike version: ^3.16.6

Installing aerospike on Ubuntu 16 seems to fail. We noticed this in our build pipeline and it seems that it tries to download  the C library from a invalid url as seen below:

`info: downloading 'https://artifacts.aerospike.com/aerospike-client-c/4.6.23/aerospike-client-c-libuv-4.6.23.ubuntu16.04.x86_64.tgz' to 'aerospike-client-c-libuv-4.6.23.ubuntu16.04.x86_64.tgz'`

Currently, accessing this url will throw a 404 response. Replacing os version in the URL with `..ubuntu18.04.x86_64.tgz` will make the archive valid.

Any ideas on how we should fix this without upgrading the distro version?

**Comment by unreadable** [comment]
As seen in the installation [doc](https://docs.aerospike.com/docs/operations/install/tools/ubuntu/), at least Ubuntu 18 is required. Pretty much ubuntu 16 is no longer supported.

**Comment by jhecking** [comment]
You are right: Support for Ubuntu 16.04 has been removed from the client. Client version 3.16.5 was the last version that supported it. You could consider downgrading your version from the latest 3.16.6 to 3.16.5: https://github.com/aerospike/aerospike-client-nodejs/blob/master/CHANGELOG.md#3166---2021-07-13
