### ISSUE TITLE
how long will update node v0.12?

### ISSUE THREAD

**Issue by tungtouch** [aerospike/aerospike-client-nodejs#44]
Hi team,
i want to ask, how long will update node v0.12?

Thanks !!!

**Comment by blitzprog** [comment]
I'm also waiting for a v0.12 update before I can use this.

**Comment by blitzprog** [comment]
Sorry I don't mean to be rude, but is there an ETA for node.js 0.12 support?

I'm asking this because I'd really love to use Aerospike but I need to decide on a database system over the next days.

**Comment by mindnuts** [comment]
:+1: to this. 0.12 is the latest stable version and i can't think of a reason not to move to it. Any reason why you still support old 0.10.33 version?

**Comment by mathias234** [comment]
I want this

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

We are prioritizing v0.12 compatibility. We are planning to make an official release in next two weeks time.

Thanks.

**Comment by blitzprog** [comment]
Awesome news.
If there is anything I can help with, be it alpha-testing or even coding/bug-fixing, feel free to contact me.
I'm very interested in 0.12 support so if I can save you time in any way please let me know :)

**Comment by pilwon** [comment]
We really need v0.12 support to use it in our app. Do we have any update on this issue?

**Comment by GayathriKaliyamoorthy** [comment]
We just released in our official aerospike repository and also in npm with changes for node v0.12 compatibility. Please try this and give your feedback.
