### ISSUE TITLE
Comments and suggestions

### ISSUE THREAD

**Issue by tracker1** [aerospike/aerospike-client-nodejs#45]
1. The first comment, and something that really seems alien is seeing an error object when there wasn't an error... this really breaks node convention of only having to check for the existence/truthiness of an error, not inspection.  It really isn't an error in your implementation.  This breaks a lot of utilities that people use to improve their flows such as promisify libraries/methods.

2. Given the fast movement of io.js and changes to Node 0.12, I'm somewhat surprised that the newer versions aren't supported... I'm not familiar with the protocol, but how difficult would it be to move to a JS based client implementation that isn't dependent on a binary module?  I know that this may well not perform quite as fast as the native module, but the trade-off may be well worth it considering how quickly io.js is now moving.

3. It may be worthwhile to implement a promise based client over the top of the base client (where that implementation checks that the status code is okay before resolving/rejecting the promise).  Considering this is where development is moving.

4. It wasn't immediately obvious if the client implements or needs separate pooling for use with multiple simultaneous requests.

Feel free to break these off into separate issues.. I wanted to open dialog first, and make a couple of suggestions.

**Comment by GayathriKaliyamoorthy** [comment]
1. Regarding error object - We are seriously considering the implications of moving to model where we do not return error codes. The current users of this module have designed around this model where an error object is returned. And moving away from this will break backward compatibility. We will discuss internally and keep you posted.

2.Regarding node v0.12.0 compatibility - We are in the process of integrating with Nan module, so that Aerospike module is compatible with both node v0.10.* and node v0.12.*. This will be released within this week.

3. Regarding promise based implementation, We discuss this internally and prioritize, meanwhile we accept pull requests from community, so feel free to contribute :)

4.When you say pooling, do you mean connection pooling?

**Comment by tracker1** [comment]
1. it's fine to return error codes... when there's an error... when the result is "OK" I wouldn't expect an err object at all... this seriously breaks node callback convention.

2. awesome, I'm assuming you'll also test against iojs?

3. cool

4. Yes, I mean connection pooling... ie: an example of how best to use the client, when making multiple requests... does your module implement connection pooling, or would one have to create a wrapper around say `generic-pool` and handle pooling oneself?

**Comment by GayathriKaliyamoorthy** [comment]
1. We will consider this seriously and come up with a solution for this.

2. I am not testing against iojs for now, but in the subsequent release I'll test and release note it.

4. Yes we do connection pooling in the underlying implementation. The number of connections that are opened can be configured when creating an aerospike object. By default, there are 300 connections maintained in the connection pool. If the client has to serve more than 300 connections, new connections are opened and reused.

Thanks

**Comment by revington** [comment]
+1 for the "do not return an error when there is no error" 
Also, all the error codes are not specified in the docs like the {code: -1, message: 'Failed to see cluster'}.

Is there any way to disable client->log ? When I can not connect to the cluster this line is sent to stderr
`Apr 29 2015 10:53:08 GMT: ERROR(8478) [connect.cc:69] [Connect] - Connecting to Cluster Failed`

**Comment by streamich** [comment]
+1 for not using underlying C driver but implement the protocol in pure JS.

Also, open source the protocol, if it is not.

**Comment by bbulkow** [comment]
The protocol has been defined, and both the client and server are open source, so anyone is able to write a client. Anyone who would like to write a pure JS client is welcome to.

**Comment by GayathriKaliyamoorthy** [comment]
All issues in this discussion are addressed except for promise support. For updates on promise support refer issue #78 . Closing this issue.
