### ISSUE TITLE
error: Linux distribution not supported: 'ubuntu22'

### ISSUE THREAD

**Issue by PorubenkoEugene** [aerospike/aerospike-client-nodejs#462]
Please add Ubuntu 22 support, as soon as possible!!! Thanks!

**Comment by Nazar910** [comment]
Same issue for me

**Comment by realmgic** [comment]
See an example to how to build the client manually on Ubuntu 22.04 here: https://github.com/aerospike/aerospike-client-nodejs/commit/68e40f408048d4c8f54d1cb4d1eb18a5b401a332

**Comment by PorubenkoEugene** [comment]
Thanks for the feedback! I close this issue. Just updated to version 4 )))
