### ISSUE TITLE
Typescript file missing in npm package?

### ISSUE THREAD

**Issue by Aconradty** [aerospike/aerospike-client-nodejs#465]
I would like to use the types included since version 4.x but it looks like they are not included in the npm package.
Is this a mistake?

Thanks in advance

**Comment by jhecking** [comment]
The new files need to be included here: https://github.com/aerospike/aerospike-client-nodejs/blob/702d60c7e6b8821541a165df3cc01a357e2451b3/package.json#L86-L96

@rpandian-spike

**Comment by rbotzer** [comment]
This should be fixed in [client releases](https://download.aerospike.com/download/client/nodejs/notes.html) 4.0.3 and 5.0.1.
