### ISSUE TITLE
Fix code scanning alert - Clear-text logging of sensitive information

### ISSUE THREAD

**Issue by rpandian-spike** [aerospike/aerospike-client-nodejs#474]
Tracking issue for:
- [ ] https://github.com/aerospike/aerospike-client-nodejs/security/code-scanning/1

**Comment by jhecking** [comment]
Note that the Config class prevents logging of the password via console.log via a custom `inspect` handler: https://github.com/aerospike/aerospike-client-nodejs/blob/95fb800271f4da4d9dbb1a3ada7916343e058226/lib/config.js#L558-L570 It’s not a fool-proof measure, as it only works when Node.js’ `util.inspect` function is used for logging, but it should at least prevent logging of the password by the client itself.
