### ISSUE TITLE
Incompatibility between client version 5.0.2 and Ubuntu 18.04

### ISSUE THREAD

**Issue by xom9ikk** [aerospike/aerospike-client-nodejs#483]
**Problem №1**
When trying to use the built and redistributable aerospike client binary on ubuntu 18.04, the following error occurs:
`_Error: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by /project/node_modules/aerospike/lib/binding/node-v72-linux-x64/aerospike.node )_`

GLIBC_2.28 is a dependency that is only available on Ubuntu 20.04 and above.
At the same time, the C client itself should work on 18.04.
My guess is that the binaries being distributed were built to target the 20.04 platform (or built on 20.04).
Because of this, we are unable to use this library on Ubuntu 18.04.
At the same time, when trying to build the client manually and link via npm link, everything works fine on Ubuntu 18.04.

I have a guess that the build is on Github Actions where [ubuntu-latest](https://github.com/aerospike/aerospike-client-nodejs/blob/10b26939a1ea95b0cf4e4f8885380e712c74de78/.github/workflows/linux-build.yml#L22) is used which points to 20.04

**Suggested solution:**
1) Run build binaries on ubuntu-18.04;

**Problem №2**
There was an option to work around this issue with `npm install aerospike@5.0.2 --build-from-source=aerospike` to run the `node-gyp` build process on installation to build the binaries, but most likely there is a problem in the bash script and an error occurs :
`_11 25.69 [✗] /project/node_modules/aerospike/libuv-v1.8.0/include/uv.h_`
Although libuv is installed globally.

**I see 2 solutions for this problem:**
1) Add logic to download libuv when trying to run npm i with `--build-from-source=aerospike` flag;
2) Use libuv which is installed globally;

Below I will provide docker files that can be used to reproduce the problem:
1) Trying to use prebuilt binaries;
2) Trying to build binaries with `--build-from-source=aerospike`;

<details>
  <summary>Dockerfile 1</summary>

  ```dockerfile
  FROM ubuntu:18.04

RUN apt update && apt install -yq --no-install-recommends \
        build-essential \
        curl \
        wget \
        lsb-release \
        ca-certificates \
        gcc \
        g++ \
        make \
        cmake \
        clang \
        libssl1.0.0 \
        libssl-dev \
        libuv1-dev && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt install -y nodejs

WORKDIR project
RUN npm init -y
RUN npm install aerospike@5.0.2
RUN echo "const aerospike = require('aerospike'); console.log(aerospike);" > index.js
RUN node index.js
  ```
</details>

<details>
  <summary>Dockerfile 2</summary>

  ```dockerfile
  FROM ubuntu:18.04

RUN apt update && apt install -yq --no-install-recommends \
        build-essential \
        curl \
        wget \
        lsb-release \
        ca-certificates \
        gcc \
        g++ \
        make \
        cmake \
        clang \
        libssl1.0.0 \
        libssl-dev \
        libuv1-dev && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt install -y nodejs

WORKDIR project
RUN npm init -y
RUN npm install aerospike@5.0.2 --build-from-source=aerospike
RUN echo "const aerospike = require('aerospike'); console.log(aerospike);" > index.js
RUN node index.js
  ```
</details>

**Comment by DomPeliniAerospike** [comment]
Hello @xom9ikk ,
From my recent testing, the Nodejs client can be built in Ubuntu 18, 20, and 22 with Client version 5.2.0. Ubuntu 18 now meets the GLIBC requirements of aerospike since the GLIBC version requirement is now lower.  I will close the issue, but feel free to reopen the issue if you continue to have difficulty and we can keep troubleshooting.
