### ISSUE TITLE
Centos 7

### ISSUE THREAD

**Issue by Stono** [aerospike/aerospike-client-nodejs#52]
Hi, 
Trying to do an npm install on centos7 and I'm getting:
```
$ npm install --save aerospike
\
> aerospike@1.0.37 install /storage/integration-layer/zbac/node_modules/aerospike
> node-gyp rebuild

make: Entering directory `/storage/integration-layer/zbac/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
error: centos7 is not supported.
```

Any idea?  I presume you do support RHEL7/CENTOS7?

**Comment by GayathriKaliyamoorthy** [comment]
Hi @Stono 

We made an official release version 1.0.40, enhancing the Aerospike Client nodejs to support centos7. Please give it a try and inform us in case you are still facing any issue during installations.

Thanks

**Comment by bbulkow** [comment]
Works great on my centos 7 machine. Thanks for fixing.

I would suggest putting the instructions for installing on the README .... I used a fairly standard install of using epel and epel's provided node and npm, different from @Stono 's use of the top of tree 0.12
