### ISSUE TITLE
Malloc error after "LDT-LDT Bin is Damaged"

### ISSUE THREAD

**Issue by khanhhua** [aerospike/aerospike-client-nodejs#53]
This is the error I got.
node(10093,0x7fff768b6300) malloc: **\* error for object 0x101063e00: pointer being freed was not allocated

The error occurred after the client code continues to execute after a failed LargeList add operation.

**Comment by GayathriKaliyamoorthy** [comment]
Hi @khanhhua 

Could you share the sample code that produces this error.

Thanks

**Comment by GayathriKaliyamoorthy** [comment]
Hi @khanhhua 

This error comes when non-ldt bin is used for a LDT operation. For example, when one tries to add a value to a bin, which is not LDT bin, server returns this error. 
And are you setting policy value when creating the LargeList? I tried reproducing the same error, but could not. Could you share the sample piece of code that produces this segfault to help us debug further.

Thanks

**Comment by denisbetsi** [comment]
I am getting the same error
The code is from sample node.js Answers section of the exercises
```
    // Read User record
    var key = {
      ns:  "test",
      set: "users",
      key: answer.username
    };

    // Retrieve the record using the key.
    client.get(key, function(err, record, metadata, key) {
        if(err.code===0){
          console.log("FOUND : " + JSON.stringify(record));
        }else{
          console.log("NOT_FOUND - " + JSON.stringify(err));
        }
        client.close();
    });
```

The result: 
```
? What would you like to do: Read User Record
********** Read User Record **********
? Enter username: user2341
Error : {"code":2,"message":"AEROSPIKE_ERR_RECORD_NOT_FOUND","func":"as_command_parse_result","file":"src/main/aerospike/as_command.c","line":915}
node(8707,0x7fff7d82c300) malloc: *** error for object 0x1018b4600: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Interesting enough, one time using same code and same username, the record WAS found
```
? What would you like to do: Read User Record
********** Read User Record **********
? Enter username: user241
FOUND : {"username":"user241","password":"pwd241","gender":"m","region":"s","tweetcount":0,"lasttweeted":0,"interests":["Camping","Camping","Travel"]}
node(8696,0x7fff7d82c300) malloc: *** error for object 0x102027800: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

I am on Mac OS Yosemite, using latest version of Node.js

**Comment by jhecking** [comment]
Closing out this old issue.
