### ISSUE TITLE
Error: Running aerospike client on Arm64(aarch) on MacOS

### ISSUE THREAD

**Issue by shubhamc-ins** [aerospike/aerospike-client-nodejs#535]
![image](https://user-images.githubusercontent.com/127132399/224680504-a9e289ea-8888-4075-a332-579b80154b29.png)

I'm using node 14 version and building an image which has aerospike as well. 
After running `yarn install` and `yarn build`, I'm getting above error. 

I'm not sure if this due to mac m1/m2 architecture.

**Comment by shubhamc-ins** [comment]
I also tried to run aerospike locally instead of within docker.

I followed these steps [https://developer.aerospike.com/client/nodejs/install#macos](https://developer.aerospike.com/client/nodejs/install#macos), installed the prerequisites.

OS: MacOS M2 Max
Node version: I tried it with 18.15.0 and v19

I'm again getting the same error:
![image](https://user-images.githubusercontent.com/127132399/225049001-21f4f19c-d0ec-456a-86c4-9dcda1286145.png)

Can anybody help me out here @realmgic @jhecking @DomPeliniAerospike

**Comment by DomPeliniAerospike** [comment]
Hi @shubhamc-ins 
We have updated our typings recently, and they should be more functional now. If you are still experiencing this issue, we can look into other solution paths.  Sorry for the delayed response.

**Comment by DomPeliniAerospike** [comment]
Hi @shubhamc-ins 
Our index.d.ts isn't compiling in our most recent version.  For a workaround, see: https://github.com/aerospike/aerospike-client-nodejs/issues/553

**Comment by shubhamc-ins** [comment]
@DomPeliniAerospike Thanks, I'll check this and let you know.

**Comment by DomPeliniAerospike** [comment]
Hi @shubhamc-ins,

The newly released version 5.11.0 has updated typings.  You should be able to simply `npm install aerospike` and use the package with typescript. We've also added yarn testing as well as typescript testing to our pipeline, so hopefully this issues can be avoided in the future.

I will close the issue now, but feel free to reopen if you are still having issues with yarn and typescript.

**Comment by shubhamc-ins** [comment]
Hi @DomPeliniAerospike, I just tried rebuilding on my Mac m2 and I'm still facing the same error.
![image](https://github.com/aerospike/aerospike-client-nodejs/assets/127132399/5f618560-1450-4814-a5c9-19b943a88f64)

**Comment by shubhamc-ins** [comment]
Apparently, everything works fine on my Linux machine. I have 5.0.0 version over there and I don't face any typings issue while building the application there.
