### ISSUE TITLE
client.add() issues

### ISSUE THREAD

**Issue by DamilolaJegede** [aerospike/aerospike-client-nodejs#60]
`client.add(key, bins, function(error, record))` returns an empty record set `{}` in `console.log` and subsequent calls to `record.anything` returns `undefined`.

**Comment by DamilolaJegede** [comment]
client.add() was just also removed from the docs! Like, right now. Are you no longer supporting it?

**Comment by GayathriKaliyamoorthy** [comment]
`client.add()` API is supported. But it is a documentation bug. The callback returns only error not the record. Sorry for the inconvenience. The documentation will be updated in the next release.

Thanks

**Comment by DamilolaJegede** [comment]
Alright, great. Thanks.
