### ISSUE TITLE
memory leak when using over 14 character bin name

### ISSUE THREAD

**Issue by KasakiNagato** [aerospike/aerospike-client-nodejs#61]
Currently the max length of bin name is 14 characters in aerospike.
And when I use over 14 characters as a bin name, that bin is ignored and memory leak occurs.

For example:

```
var record = {
  over_14_character_bin_name: 'foo'
}
client.put(key, record, function(error, key) {
  // bin 'foo' is not stored and memory leak occurs
});
```

So I think there are 2 problems:

1. Aerospike Node.js Client should validate the length of bin name.
2. Aerospike C Client should free memory when bin name is over 14 characters.

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

We have identified the problem and working on the fix. Will be available as part of next release.
Sorry for the inconvenience.

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

We made an official release containing the fix for this issue. The current behavior is, when a bin name with length more than 14 characters are passed, the Put API call fails with error `AEROSPIKE_ERR_PARAM`. Please upgrade the client and let us know your feedback.

Thanks

**Comment by KasakiNagato** [comment]
Hi,

Thank you for your rapid response!
I correctly get the following error with version 1.0.41:

```
Jun 17 2015 00:06:39 GMT: ERROR(4183) [conversions.cc:872] [recordbins_from_jsobject] - Valid length for a bin name is 14. Bin name length exceeded
Jun 17 2015 00:06:39 GMT: ERROR(4183) [put.cc:120] [prepare] - Parsing as_record(C structure) from record object failed
{ code: -2,
  message: 'AEROSPIKE_ERR_PARAM',
  func: '',
  file: '../src/main/client/put.cc',
  line: 121 }
```

Thanks
