### ISSUE TITLE
batchGet() hangs if connection closes and there are outstanding call backs

### ISSUE THREAD

**Issue by denisbetsi** [aerospike/aerospike-client-nodejs#63]
To simulate

```
 
    for(k=1;k<50;k++){
      keys.push({ns:"test",set:"users",key:"user" + k});
    }

    /* Get all users */
    client.batchGet(keys, function (err, results) {
        var i = 0;
        if ( err.code == status.AEROSPIKE_OK ) {
            for ( i = 0; i < results.length; i++ ) {
                switch ( results[i].status ) {
                    case status.AEROSPIKE_OK:
                        // Get tweets
                        var record = results[i].record;
                         var tweet_keys = [];
                        console.log(record.username + ' has ' + record.tweetcount + ' tweets');
                        for (var t=1;t<=record.tweetcount;t++){
                          tweet_keys.push({ns:"test",set:"tweets",key:record.username + ":" + t});
                        }
                        if(tweet_keys.length>0)
                          client.batchGet(tweet_keys,function(terr,tresults){
                          if(terr.code!=0){ console.log('Tweet error : ' + JSON.stringify(terr))};
                          tresults.forEach(function(tweet){
                            if(tweet['record'])
                              console.log('Tweet ' + JSON.stringify(tweet.record));
                          });
                        });
                        break;
                    case status.AEROSPIKE_ERR_RECORD_NOT_FOUND:
                        console.log("NOT_FOUND - ", results[i].keys);
                        break;
                    default:
                        console.log("ERR - %d - ", results[i].status, results[i].keys);
                }
            }
        }
        else {
            console.log("ERR - ", err);
        }    
        client.close();
    });    
```

client.close() will be executed after about 3 results and the rest of the batchGet requests will wait for a response never reaching any sort of a timeout.

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

`client.close()`  should be invoked only when all the operations that are performed using the client object is completed. The semantics of  `client.close()` is release all the resource associated with client object. The resources include all the open connections and memory allocated for the client object. Once these resources are released, the client can no longer communicate with Aerospike Server and thus the processing stops.   

In the above code snippet, you are not waiting for callback to be invoked by the `  client.batchGet(tweet_keys,function(terr,tresults){}` for this batchGet invocation. The `client.close()` function must be invoked after processing this inner callback. 

Thanks.

**Comment by denisbetsi** [comment]
Absolutely, I realize that. I am just saying that, those call backs in the forloop do not get terminated, the code gets stuck in the forever unending dead end. If the connection drops for whatever reason and has similar functionality to client.close() will it mean that worker with all those unresolved call backs be stuck the same way?

**Comment by GayathriKaliyamoorthy** [comment]
@denisbetsi 

Regarding the connection dropping for any reason, the underlying driver handles that case. `Client` object stores the callback passed for the batchGet API and invokes it when the operation is completed. If the client object is destroyed, then the behavior is undefined.

Thanks
