### ISSUE TITLE
how to stop scan?

### ISSUE THREAD

**Issue by fooevr** [aerospike/aerospike-client-nodejs#64]
how to stop scan when a get data in stream.on('data', function(){})?

**Comment by GayathriKaliyamoorthy** [comment]
Hi @fooevr,

To clarify your questions, are you looking for ways to not consume all the data returned by stream?

**Comment by GayathriKaliyamoorthy** [comment]
Closing this due to non activity for a prolonged period.

**Comment by cogmeta** [comment]
stream.abort()
