### ISSUE TITLE
random scan_id not random enough

### ISSUE THREAD

**Issue by courtneycouch** [aerospike/aerospike-client-nodejs#66]
If this: 

https://github.com/aerospike/aerospike-client-nodejs/blob/80d423ff00dd7010a9038b754f386d777a0ed481/src/main/client/query_foreach.cc#L467-L471

gets hit more than once in a second then the scan_id gets duplicated and you end up with errors like:

`WARNING (scan): (thr_tscan.c::807) not starting scan 1926250993 because rchash_put() failed with error -4`

It's not likely to happen in production but for pre-deployment testing it's possible for scans to happen very close together (as fast as tests complete). So we're finding we have to put these silly 1 second delays to keep scan_id collisions from happening.

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

We do not expect multiple requests for full system scan within a second. If you have such requirements, we can enhance the API, to accept scanID from the application. You can raise a pull request with the enhancements. We accept pull requests. :)

Thanks.

**Comment by tracker1** [comment]
I'm not familiar with the internals, but if the scanID isn't sequential, why isn't crypto randomBytes, or the `uuid` module not used?

**Comment by wchu-citrusleaf** [comment]
We will be fixing this shortly

**Comment by GayathriKaliyamoorthy** [comment]
Fix is available from release [1.0.49](https://github.com/aerospike/aerospike-client-nodejs/releases/tag/1.0.49).
