### ISSUE TITLE
Build fails with iojs 2.1.0

### ISSUE THREAD

**Issue by extra-0** [aerospike/aerospike-client-nodejs#67]
Below is the output for the build part of npm install aerospike on iojs 2.1.0

    CHECK
       [✓] /usr/src/app/node_modules/aerospike/aerospike-client-c/package/usr/lib/libaerospike.a
       [✓] /usr/src/app/node_modules/aerospike/aerospike-client-c/package/usr/include/aerospike/aerospike.h
       [✓] /usr/src/app/node_modules/aerospike/aerospike-client-c/package/opt/aerospike/client/sys/udf/lua/aerospike.lua

      TOUCH Release/obj.target/aerospike-client-c.stamp
      CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
    In file included from ../node_modules/nan/nan_new.h:181:0,
                     from ../node_modules/nan/nan.h:74,
                     from ../src/main/aerospike.cc:18:
    ../node_modules/nan/nan_implementation_12_inl.h: In static member function 'static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)':
    ../node_modules/nan/nan_implementation_12_inl.h:172:76: error: no matching function for call to 'v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)'
       return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                                ^
    ../node_modules/nan/nan_implementation_12_inl.h:172:76: note: candidate is:
    In file included from /root/.node-gyp/2.3.0/src/node.h:42:0,
                     from ../src/main/aerospike.cc:17:
    /root/.node-gyp/2.3.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
       static Local<Signature> New(
                               ^
    /root/.node-gyp/2.3.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
    aerospike.target.mk:139: recipe for target 'Release/obj.target/aerospike/src/main/aerospike.o' failed
    make: *** [Release/obj.target/aerospike/src/main/aerospike.o] Error 1
    make: Leaving directory '/usr/src/app/node_modules/aerospike/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.13.0-37-generic
    gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /usr/src/app/node_modules/aerospike
    gyp ERR! node -v v2.3.0
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok 
    npm info aerospike@1.0.43 Failed to exec install script
    npm ERR! Linux 3.13.0-37-generic
    npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "aerospike"
    npm ERR! node v2.3.0
    npm ERR! npm  v2.11.1
    npm ERR! code ELIFECYCLE

    npm ERR! aerospike@1.0.43 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the aerospike@1.0.43 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the aerospike package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls aerospike
    npm ERR! There is likely additional logging output above.
    npm info preuninstall aerospike@1.0.43
    npm info uninstall aerospike@1.0.43
    npm info postuninstall aerospike@1.0.43

    npm ERR! Please include the following file with any support request:
    npm ERR!     /usr/src/app/npm-debug.log

**Comment by GayathriKaliyamoorthy** [comment]
We do not officially support iojs for now. We are accepting pull requests from outside. Please feel free to raise pull requests, if you have ported and tested the necessary changes for the driver to be iojs compatible.

Thanks

**Comment by extra-0** [comment]
It seems like simply updating dependency version for nan module fixes the problem. I'll try to run tests and create a pull request should everything be ok.

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

We have made an official release that supports iojs. The latest version 1.0.45 should work for iojs. Please try and let us know your feedback.

Thanks

**Comment by extra-0** [comment]
Everything seems to be fine.
Thanks!
