### ISSUE TITLE
error: oracleserver7 is not supported

### ISSUE THREAD

**Issue by alangibson** [aerospike/aerospike-client-nodejs#76]
When trying to build Aerospike client 1.0.47 for node.js on Oracle Linux 7, I get the following error

```
make: Entering directory `/var/lib/jenkins/jenkins-slave/workspace/PROXY3-monitorwebapi/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
error: oracleserver7 is not supported.
make: *** [aerospike-client-c/lib/libaerospike.a] Error 1
```

Looking at aerospike-client-c.sh, it is pretty clear that Oracle Linux 7 is not on the supported list. It is however basically a rebranding of of RHEL 7, which is supported.

Assuming you don't have lsb_release (from the redhat-lsb-core package) installed, the workaround is simply:

```
touch /etc/centos-release
```

However, it would be nice to have oracleserver7 in the list of officially supported distros.

Related to: https://github.com/aerospike/aerospike-client-nodejs/issues/57

**Comment by jhecking** [comment]
OS detection has been much improved in recent client releases. But for some reason I have not been able to get any of the Oracle Linux 7 Vagrant boxes to work so I was not able to verify whether the client installation is working now or not.

I am going to close this issues but please feel free to re-open if installation on Oracle Linux 7 is still failing. If Oracle Linux is using a `/etc/os-release` file it would be great if you could upload a copy of this file to [zyga/os-release-zoo](https://github.com/zyga/os-release-zoo).
