### ISSUE TITLE
Version Lock Aerospike.

### ISSUE THREAD

**Issue by mullanaphy** [aerospike/aerospike-client-nodejs#77]
We were using 1.0.21, however that seems to now fail since the build script always looks for latest version.

to test:

npm install aerospike@1.0.21

So, although we have specific versioning set, the aerospike c client that gets installed has breaking changes.

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

The latest release doesn't look for latest C client. Last few releases uses specific version of C client.
If you would like to avoid upgrading to latest C client, you can set Custom path for C client dependency.
Here is the documentation to set custom path.
https://github.com/aerospike/aerospike-client-nodejs#custom-search-path
