### ISSUE TITLE
Promises support

### ISSUE THREAD

**Issue by d5** [aerospike/aerospike-client-nodejs#78]
Do you have any plans to support [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) in the official client driver? I've made one for my own projects ([aerospike-p](https://github.com/d5/aerospike-p)), but, I guess many others have the  same needs.

**Comment by IncSW** [comment]
You can write benchmarks callbacks vs promises. I think you will see that promises are too slow.

**Comment by d5** [comment]
That's fair. Promises are slow but that's well known to those who use them. I think Promise pattern (and/or with generators) is still the best way to avoid callback hells and to improve error handling in Node.js. Benchmarking is a great idea because that will allow people to make informed trade-offs.

**Comment by d5** [comment]
I did a quick benchmarks. I tried to minimize the [code changes](https://github.com/d5/aerospike-p/commit/c31fa4c64e514ad597cb87df1d47894f57398dd5), and, here's the result.

- [non-promisified](https://github.com/aerospike/aerospike-client-nodejs) (original)
  - duration: **14.49ms**
  - tps/process: **6.902**
- [promisified](https://github.com/d5/aerospike-p)
  - duration: **14.597ms**
  - tps/process: **6,856**

_See [here](https://gist.github.com/d5/c9e4e8ea65b38874923f) for the full output._

With a simple benchmark, it's hard to tell what this really means. But, I do use promises + generators in my production code a lot, and, usage of promises itself was not been a bottleneck in large scale environments.

**Comment by IncSW** [comment]
I'm write [benchmark](https://gist.github.com/IncSW/924df392de7aaf8ef9e8). Not a best benchmark code, but difference up to 2 times...

And in typical cases code with promises not a better then with callbacks.

**Comment by IncSW** [comment]
Yes, if checking promises vs callbacks with other logic then promises overhead is too small.
But in typical cases code with promises not a better then with callbacks when using aerospike.

**Comment by nullivex** [comment]
Why not just wrap the client with Bluebird?

**Comment by djMax** [comment]
+1 for promise support... They're native in v8 now, but the "wrapping" concept that Bluebird does nicely is not.

**Comment by ScionOfBytes** [comment]
+1 for Promise support.

**Comment by jhecking** [comment]
I've started exploring an implementation of Promises for the client in #210. This is work in progress and I'm looking for feedback about the design and implementation of the feature.

**Comment by jhecking** [comment]
I have just merged support for Promises (#210) back into the master branch. This will be included in the upcoming v3 release of the client. (Release date still TBD and pending further changes.)

It would be great if anyone interested in the feature could check out the new interface. This [list of API changes](https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/api-changes.md#version-300) contains more details about some of the (breaking) changes in the new v3 client API.
