### ISSUE TITLE
AEROSPIKE_ERR_REQUEST_INVALID

### ISSUE THREAD

**Issue by fed135** [aerospike/aerospike-client-nodejs#79]
Just installed Aerospike on a private cloud, which is behind a proxy, and I'm having trouble making requests.

I keep getting: 

    Error  :  { code: 4,
      message: 'AEROSPIKE_ERR_REQUEST_INVALID',
      func: 'as_query_parse_records',
      file: 'src/main/aerospike/aerospike_query.c',
      line: 228 }

Which translates to a 501 - protocol error (correct?)
Checked security group, checked service status, everything seems to be fine.

    // Connect to the cluster.
    var client = aerospike.client({
        hosts: [ { addr: 'x.x.x.x', port: 3000} ]
    });

    /**
     * Connects to cache server
     */
    function connect() {
    	var cl = K.getComponent('console');

	client.connect(function(err) {
		if (err.code !== STATUS.AEROSPIKE_OK) {
			cl.error('Could not connect to Cache server');
		}
		else {
			cl.log('Everything ok!');
		}
	});
    }

I get 'Everything ok!', when connecting, then I call:

    //key: 'fieldA'
    //timeframe: {start: 1436800200000, end: 1438009800000}
    var query = client.query('cache', key, {
        filters: [
            FILTER.range('id', timeframe.start, timeframe.end)
        ]
    });
    var queryStream = query.execute();
    queryStream.on('data', function (rec) {
        cl.log(rec);
    });

    queryStream.on('error', function (err) {
        cl.error(err);
    });

    queryStream.on('end', function () {
        cl.info('the end');
        callback();
    });

And I get the error.
Did some searching and I couldn't find anything on setting proxy configurations in the documentation
or in the code.

**Comment by bbulkow** [comment]
Hello Fred,
The Aerospike protocol is not based on HTTP, and thus won't pass through an HTTP proxy. If you need HTTP service, I would recommend writing a small HTTP service that speaks to your Aerospike cluster, and running that service behind the proxy. Does that make sense, or do you have a TCP & NAT based network?

**Comment by fed135** [comment]
Ugh, Monday mornings, I don't know why I have figured this out. Thank you for your help.
