### ISSUE TITLE
Problem installing Aerospike driver with Iojs.

### ISSUE THREAD

**Issue by NawarA** [aerospike/aerospike-client-nodejs#80]
Build fails on the latest version of iojs. The client works with 1.8.x but not the 2.x releases. 

The client must remain compatible with the latest stable versions of node and iojs.

The iojs 2.x branch is going to become node.js. It's very important to upgrade the client to support the latest versions of iojs and v8

**Comment by tracker1** [comment]
I suspect nan just needs to be updated to the latest version... (assuming nan is used to support the binary module)

**Comment by GayathriKaliyamoorthy** [comment]
Hi @NawarA 

I have tested it on iojs version 2.3.2. It builds and all the tests are passing. Could you give more details about the build failure. That would help us debug this issue.

Thanks.

**Comment by NawarA** [comment]
The library is now compatible. Good work.

**Comment by nikhil32** [comment]
Hi I am trying with iojs 1.7.1, 2.5.0, 3.0.0 with aerospike 1.0.45/50. There is no issue wrt build, but when running I am getting following error

 Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/nikhil/git/project/API/node_modules/aerospike/lib/aerospike.js:1:72)

Can some one help me with this
