### ISSUE TITLE
Feature request: stop printing directly to stdout

### ISSUE THREAD

**Issue by fed135** [aerospike/aerospike-client-nodejs#82]
It is common knowledge for Node library developers to avoid 'console.log' calls and similar. 

It is strongly recommended that https://www.npmjs.com/package/debug be used.
This way out terminal windows don't get polluted.

I've looked a bit into implementing it myself, but not being a C++ programmer, things got complex really  fast. The way I see it, the addon could export a function to which the node client could pass the debug method.

something like:

```
var stdErr = require('debug')('aerospike:error');
var stdOut = require('debug')('aerospike');

as.setDebugMethods({
    error: stdErr, 
    log: stdOut
});
```

and to see the logs, you would run

```$ DEBUG=aerospike npm start```

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

Yeah, we should avoid printing to console. And in the latest release 1.0.49, we removed the code that prints to console. We are in general thinking about a logger for the library files. I am considering winston and debug. Winston seems to be feature rich and Debug easy to use. Do you have any preference or input on this.

Thanks

**Comment by fed135** [comment]
For the moment, I would have to say debug. I offers essentially the same features, without going overboard with logging to file (which is something you could push right now, or at a later time). Debug is also easier for people who have to do DevOps (like me) to configure and manage.
