### ISSUE TITLE
Memory leak in secondary index query processing.

### ISSUE THREAD

**Issue by GayathriKaliyamoorthy** [aerospike/aerospike-client-nodejs#83]
@maxvgi  Currently I'm working on this issue, and also optimizing the memory footprint for Aerospike Query API. Will make an official release after fixing and running a longevity test with this fix. Sorry for the inconvenience.

**Comment by GayathriKaliyamoorthy** [comment]
@maxvgi,

We found the reason and fixed. We are doing our internal testing. We will make an official release within this week. 

Thanks

**Comment by maxvgi** [comment]
Looking forward to the release to test it
@GayathriKaliyamoorthy, thank you for your job.

**Comment by GayathriKaliyamoorthy** [comment]
Hi @maxvgi 

We made an official release [1.0.49](https://www.npmjs.com/package/aerospike) with the fix. Please update and give us your feedback.

Thanks

**Comment by maxvgi** [comment]
Memory leak still persists in 1.0.49, but

I confirm the fix of the issue in 1.0.50
Furthermore, I discovered some speed increase.
Thank you!
