### ISSUE TITLE
After a few hours of normal operation, client is unable to reconnect to the database.

### ISSUE THREAD

**Issue by 0nix** [aerospike/aerospike-client-nodejs#86]
I used the aerospike NodeJS client in conjunction with Express and Passport in order to store user data. After one to four hours of normal activity, my server is unable to connect to the database, rendering the following error: `[connect.cc:69] [Connect] - Connecting to Cluster Failed` At every single time a database connection is attempted. I went to the Aerospike community forums and they suggested getting rid of the calls to `client.close()` as they were intended for a process SIGINT. I did so, and the problem persisted. I instead opted to connect to a local aerospike server instead of connecting to another one remotely, but to no avail. I have no idea what I'm doing wrong. Here is a sample of the code I use the AS Client in:

     app.get("/api/content/:id",function(req,res){

    aero.client(aeroSec.generateConfig()).connect(function(err, db){

        if(err.code != aero.status.AEROSPIKE_OK)  return res.status(403).send();

        var options = {};

        options.filters = [filter.equal("secindex", req.params.id)];

        var query = db.query("ns","posts",options);

        var data;

        var s = query.execute();

        s.on("data",function(rec){

           data = rec;

        });

        s.on("error",function(err){

            data = err;    

        });

        s.on("end",function(){

           if(data == undefined) res.status(404).send("NOTHING FOUND");

           else res.status(200).send(data);

        });   

    });

     });

**Comment by GayathriKaliyamoorthy** [comment]
According to the code, you are creating one client object for every request. The client object should be created only once and should be reused. Client object creates a connection pool with size 300. Creating many client object will lead to opening too many connection. 

    aero.client(aeroSec.generateConfig()).connect(function(err, db){
       app.get("/api/content/:id",function(req,res){
         if(err.code != aero.status.AEROSPIKE_OK)  return res.status(403).send();
         var options = {};
         options.filters = [filter.equal("secindex", req.params.id)];
         var query = db.query("ns","posts",options);
         var data;
         var s = query.execute();
         s.on("data",function(rec){
                 data = rec;
         });
          s.on("error",function(err){
                 data = err;    
           });
           s.on("end",function(){
                 if(data == undefined) res.status(404).send("NOTHING FOUND");
                 else res.status(200).send(data);
            });   
       });
     });

**Comment by 0nix** [comment]
Will try your suggestion. Closing issue as it pertains to a use case, not the library.

**Comment by GayathriKaliyamoorthy** [comment]
The same question is available with solution in [stackoverflow] (http://stackoverflow.com/questions/32193275/aerospike-works-ok-for-1-4-hours-before-defaulting-to-a-connection-error/32219882#32219882)
