### ISSUE TITLE
Fails to build with iojs >= 3 (Mac)

### ISSUE THREAD

**Issue by rschmukler** [aerospike/aerospike-client-nodejs#87]
On iojs >= 3 the node bindings fail to build. Please see the [log here](https://gist.github.com/rschmukler/e8aa56bb279f5ee163ad). With the official merger of iojs/node coming in September, it'd be great to have this working!

Unfortunately, I'm not terribly familiar with C++ or I'd attempt a PR.

Thanks for all your work.

**Comment by GayathriKaliyamoorthy** [comment]
Hi @rschmukler 

We are actively following up on Iojs compatibility of Aerospike nodejs driver. Aerospike uses [NaN module]( https://www.npmjs.com/package/nan) for maintaining compatibility with various versions of node.js and iojs. Currently we are using NaN `1.0.84`. Upgrading NaN to version `2.0.x` would solve this compilation failure with iojs 3.x. But NaN `2.0.x` is not backward compatible with `1.x`. 
We will do the necessary changes and make an official release after testing.  Thanks for bringing this up.

Thanks
Gayathri.

**Comment by GayathriKaliyamoorthy** [comment]
The latest release `aerospike@1.0.51` compiles with Iojs 3.x .

Thanks.
