### ISSUE TITLE
Adopt StandardJS coding style

### ISSUE THREAD

**Issue by jhecking** [aerospike/aerospike-client-nodejs#99]
We didn't follow any specific coding style so far and it shows in the code base. A mixture of spaces and tabs is used for indentation, the placement of curly braces is not always consistent, etc. It would be good to have a consistent coding style throughout the entire code base. The specific "rules" of the style are not as important as the consistent application of the same.

The "JavaScript Standard Style" (http://standardjs.com) seems like a good choice because it's followed by a large number of existing modules and because the `standard` module can be used to check compliance with the style easily.

All code in the project incl. the `aerospike` lib, tests, examples, benchmarks and any code snippets in the documentation should be updated to follow the coding style.

**Comment by mrbar42** [comment]
Per haps this can help as well:
http://editorconfig.org

**Comment by jhecking** [comment]
Thanks for the suggestion! Adding a `.editorconfig` file to the project sounds like a good idea.
